#!/usr/bin/env python3
"""Add every user-facing string found in the codebase audit to the String Catalog."""

import json
from pathlib import Path

TARGET_LANGUAGES = [
    "en", "it", "es", "fr", "de", "pt", "ja", "ko", "zh-Hans", "zh-Hant",
]

ALL_STRINGS = [
    # DeletionMode
    "Move to Trash",
    "Permanently Delete",
    "Safer option. Files can be recovered from the Trash.",
    "Removes files immediately and cannot be undone.",
    "Delete Permanently",
    # RemovalCategory
    "Application",
    "Application Support",
    "Caches",
    "Preferences",
    "Saved State",
    "Logs",
    "Containers",
    "Group Containers",
    "Cookies",
    "WebKit Data",
    "HTTP Storage",
    "Temporary Files",
    "Launch Agents",
    "Launch Daemons",
    "Login Items",
    "Extensions",
    "Crash Reports",
    "Spotlight Metadata",
    "QuickLook Plugins",
    "Privileged Helpers",
    "Widgets",
    "Other Support Files",
    # SimulationResult StorageBucket
    "Support Files",
    "Other",
    # SimulationResult reportStats
    "Total Files",
    "Recoverable",
    "Categories",
    "Background Components",
    "Services",
    "Estimated Time",
    # UpdateModels
    "Network error: %@",
    "Couldn't read the release information from GitHub.",
    "GitHub rate limit reached. Please try again later.",
    "The latest release has no downloadable DMG.",
    "The update came from an untrusted source and was blocked.",
    "Couldn't mount the downloaded disk image.",
    "The disk image didn't contain Uninstally.",
    "Update verification failed: %@",
    "Couldn't install the update: %@",
    "The update was cancelled.",
    # HistoryRetention
    "30 Days",
    "90 Days",
    "1 Year",
    "Forever",
    # HistoryFilter
    "Today",
    "Last 7 Days",
    "Last 30 Days",
    "All Time",
    "Permanent Delete",
    # SortOption
    "Install Date",
    "Recently Used",
    "Unused",
    "Largest Apps",
    # SmartFilter
    "All Applications",
    "Largest",
    "Recently Installed",
    "Recently Opened",
    "Never Opened",
    "With Leftover Files",
    "Broken Installs",
    "Duplicated Across Drives",
    # SettingsSection subtitles
    "Keep Uninstally up to date.",
    "How Uninstally looks and where it lives.",
    "Choose the language used throughout the app.",
    "What happens when you remove an app.",
    "How thoroughly Uninstally searches for related files.",
    "Confirmations and safe-removal safeguards.",
    "Power-user options and resets.",
    "Version and links.",
    # Onboarding
    "Welcome to Uninstally",
    "The cleanest way to completely remove apps and every file they leave behind.",
    "Smart Detection",
    "Uninstally matches files by bundle identifier — not just by name — across every Library location, so nothing gets missed and nothing unrelated gets touched.",
    "Safe by Design",
    "You review everything before it's removed. Files go to the Trash where possible, and admin actions ask for permission only when needed.",
    "Skip",
    "Get Started",
    "Search leftovers",
    "Rescan",
    "Scanning for orphaned files\u2026",
    "No Leftovers Found",
    "Your Mac is tidy \u2014 no orphaned files from uninstalled apps were detected.",
    "Orphaned Files",
    "Select All",
    "Deselect All",
    "Remove Selected",
    "Remove %lld leftover items?",
    "Remove %lld Items",
    "%@ will be permanently deleted. This cannot be undone.",
    "%@ will be moved to the Trash.",
    "Reveal in Finder",
    # History
    "Search history",
    "Couldn't Restore",
    "No Uninstall History",
    "Apps you remove with Uninstally will appear here, so you can review or restore them.",
    "Filter history",
    "Clear all history",
    "Restore from Trash",
    "View Details",
    "Reveal Original Location",
    "Remove From History",
    "Apps Uninstalled",
    "Uninstalled",
    "Storage Recovered",
    "Last Uninstall",
    "Average Recovered",
    "Files Removed",
    "Original Location",
    "Deletion Method",
    "No longer in the Trash",
    "Move the app back to its original location",
    "Reveal Location",
    # Uninstall
    "Security Summary",
    "This will permanently delete the selected apps. This action cannot be undone.",
    "The selected apps and their files will be moved to the Trash.",
    "Uninstall %@?",
    "Delete %lld Apps",
    "Uninstall %lld Apps",
    "Batch Uninstall",
    "%lld applications \u2022 about %@ reclaimable",
    "Removing %@",
    "%lld of %lld",
    "Batch Complete",
    "Removed %lld applications",
    "Reclaimed",
    "Successfully Removed",
    "Removed with Issues",
    "Time Taken",
    "This window will close automatically.",
    "%lld items could not be removed",
    "%lld Applications Selected",
    "Uninstally simulated each app. Nothing has been deleted.",
    "%lld files",
    "%lld files across %lld apps",
    "Review Individually",
    "Uninstall All",
    "Copy Path",
    "Requires administrator privileges",
    "Simulating uninstall of %@",
    "percent",
    "Preparing\u2026",
    "Items",
    "Removed",
    "Remaining",
    "This install appears to be broken or incomplete",
    "Installed",
    "Last Used",
    "Identifier",
    "Location",
    "Volume",
    "Uninstall Simulation",
    "Detailed Breakdown",
    "No matching files",
    "Search files",
    "This simulation has not deleted any files.",
    "%lld of %lld items",
    "Proceed with Uninstall",
    "Related Files",
    "Login Items Removed",
    "Launch Agents Removed",
    "Background Services Removed",
    "Finder Extensions Removed",
    "Cache Folders Removed",
    "Preference Files Removed",
    "Saved State Removed",
    "Uninstall Summary",
    "Storage Analysis",
    "Total Recoverable Storage",
    "Shared Resources",
    "These items may be used by other software. Review them before removing \u2014 deselect any you want to keep.",
    "Simulation Report",
    "Broken",
    "Show in Finder",
    "Open",
    "Add to Collection",
    "Remove from Collection",
    # AppBrowser
    "Search applications",
    "Scanning your applications\u2026",
    "Empty Collection",
    "No Applications",
    "Nothing matches this filter.",
    "Refreshing\u2026",
    "Refresh the application list",
    "Select multiple applications to uninstall together",
    "Sort By",
    "Swap between grid and list",
    "%lld selected",
    "About %@ reclaimable",
    "Uninstall %lld",
    # Sidebar
    "Collections",
    "New Collection",
    "Favorites",
    "Customize Sidebar",
    "Leftover Scanner",
    "Storage Insights",
    "Homebrew",
    "Hide from Sidebar",
    "Customize Sidebar\u2026",
    "Pin to Top",
    "Unpin from Top",
    "Rename\u2026",
    "Customize Collections\u2026",
    "Delete Collection",
    "Settings",
    "Open Settings",
    "Customize sidebar and Collections",
    "Collection Not Found",
    "Select a Category",
    "Rename Collection",
    "Enter a new name for this collection.",
    # Customize
    "Sections",
    "Organize the Applications sidebar and your Collections.",
    "Hidden sections stay available \u2014 they're only removed from the sidebar.",
    "Restore Defaults",
    "Create a Collection to group and categorize apps. Add apps by dragging them onto a Collection or right-clicking an app.",
    "No Collections",
    "Collections only organize apps \u2014 they never change what's installed.",
    "Drag to reorder",
    "Choose an icon",
    "Collection name",
    "Show or hide in the sidebar",
    # Homebrew
    "Search packages",
    "Homebrew Not Found",
    "Install Homebrew from brew.sh to manage command-line packages and casks here.",
    "Reading Homebrew packages\u2026",
    "Resolving dependencies\u2026",
    "Required by (will break):",
    "Depends on:",
    "No dependency relationships detected.",
    "Also remove configuration & leftover files (--zap)",
    # Settings
    "Show icon in Dock",
    "When off, Uninstally runs as a lightweight accessory with no Dock or menu-bar presence.",
    "Source language \u2014 translation ready",
    "Restart Required",
    "Restart Now",
    "Later",
    "The application needs to restart to apply the selected language.",
    "Quit after a Finder uninstall",
    "Automatically close Uninstally once a right-click uninstall finishes.",
    "Uninstall History",
    "Keep Uninstall History",
    "Record apps you remove so you can review or restore them from Recently Uninstalled.",
    "History Retention",
    "Automatically remove entries older than this.",
    "Clear History",
    "Remove every entry from the uninstall history.",
    "Clear\u2026",
    "Clear all uninstall history?",
    "This permanently removes every entry. It does not affect files already in the Trash.",
    "Include system-level files",
    "Also search /Library locations. Removing these requires an administrator password.",
    "Scan for leftovers automatically",
    "Look for orphaned files from removed apps in the background.",
    "Monitor Trash for Deleted Applications",
    "When you drag an app to the Trash in Finder, offer to remove its leftover files.",
    "Require confirmation before deleting",
    "Always show a summary and warning before anything is removed.",
    "Verified update source",
    "Updates are only downloaded from the official Uninstally repository on GitHub and verified before installation.",
    "Reset All Preferences",
    "Restore Uninstally's settings, sidebar layout and collections to their defaults. Takes effect on next launch.",
    "Reset",
    "Preferences reset. Relaunch to see all changes.",
    "Current Version",
    "Latest Version",
    "Last Checked",
    "Status",
    "Automatically Check for Updates",
    "Automatically Download Updates",
    "Receive Beta Updates",
    "Include pre-release builds from the selected channel.",
    "Check Now",
    "Clear Ignored Version",
    "Reset Update Preferences",
    "Never",
    "Update Channel",
    "Enable beta updates to choose a pre-release channel.",
    "Not checked yet",
    "Checking\u2026",
    "You're up to date",
    "Update available: %@",
    "A native macOS uninstaller by Codenta.",
    # Storage Insights
    "Installed Applications",
    "Total Installed Size",
    "Largest Installed App",
    "Total Space Recovered",
    "Apps Removed",
    "Average Space Recovered",
    "Unused Applications",
    "Largest Leftover Files",
    "Not Opened in 90 Days",
    "This Week",
    "This Month",
    "Lifetime",
    "Installed %@",
    "Opened %@",
    "Remove Leftovers",
    "Open the Leftover Scanner to review and remove orphaned files",
    "Scanning for leftovers\u2026",
    "No orphaned files found",
    "Search apps and leftovers",
    "No matching applications",
    # Storage Charts
    "Storage by Category",
    "Recovered Storage Over Time",
    "Not enough history yet",
    "Installed Apps by Developer",
    "Application Count by Category",
    "No data yet",
    # Services
    "Scanning application\u2026",
    "Searching containers, caches and preferences\u2026",
    "Searching login items, launch agents and services\u2026",
    "Validating every path\u2026",
    "Calculating storage\u2026",
    "Broken alias",
    "Scan Leftovers",
    "Dismiss",
    "Uninstall Complete",
    "Uninstall Finished with Issues",
    "Application Moved to Trash",
    "Uninstally found leftover files for %@. Would you like to remove them?",
    "The application bundle",
    "Named for %@",
    "Folder named after %@",
    "Preferences for %@",
    "Cask",
    "Formula",
    "Homebrew is not installed.",
    "Uninstall failed.",
    "Path no longer exists",
    "Protected system location",
    "Too close to a root directory",
    "Refuses to delete an approved root directory",
    "Outside every approved location",
    "Applications and related files will be moved to the Trash. You can restore them until the Trash is emptied.",
    "Applications and related files will be permanently deleted. This action cannot be undone.",
    "Could not confirm this belongs to %@",
    "Item still present after deletion",
    "Failed to remove %@: %@",
    "Uninstall\u2026",
    "Settings sections",
    "Refresh Applications",
    "Change the sort order",
    "Off",
    "On",
    "reclaimable",
    "Untitled Collection",
    "Stable",
    "Beta",
    "Nightly",
    "Update Available",
    "Largest Applications",
    "Uninstall %@",
    # Finder
    "%lld Applications Selected",
    # Notification
    "Uninstall Complete",
    "Uninstall Finished with Issues",
    "Application Moved to Trash",
    "Update Available",
    # AppInfo
    "Other",
    # Remaining
    "Recently Uninstalled",
    "Website",
    "GitHub",
    "Cancel",
    "Done",
    "Uninstall",
    "Delete",
    "Remove",
    "Name",
    "Size",
    "Developer",
    "Version",
    "Category",
    "Date",
    "Layout",
    "Filter",
    "Sort",
    "Refresh",
    "Rename",
    "Continue",
    "App",
    "Apps",
    "Trash",
    "Layout",
    "OK",
    "uninstally",
    "codenta.us",
    "Bundle Identifier",
    "Count",
    "Not checked yet",
    "Deleted",
    "Refreshing",
    "Sort",
    "Search history",
    "Filter history",
    "Select",
    "Search files",
    "Confirm",
    "Tools",
    "Check Now",
    "Checking",
]

if __name__ == "__main__":
    xcstrings_path = Path(__file__).parent.parent / "Uninstally" / "Localizable.xcstrings"
    with open(xcstrings_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    strings = data.setdefault("strings", {})
    added = 0

    for key in ALL_STRINGS:
        if key in strings:
            continue
        entry = {"localizations": {}}
        for lang in TARGET_LANGUAGES:
            # Mark en as translated, others as needs_review for now
            if lang == "en":
                entry["localizations"]["en"] = {
                    "stringUnit": {"state": "translated", "value": key}
                }
            else:
                # Placeholder — will be filled by translation script
                pass
        strings[key] = entry
        added += 1

    with open(xcstrings_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Added {added} new keys. Total entries: {len(strings)}")
