#!/usr/bin/env python3
"""Fill in every missing translation across all 9 languages."""

import json
from pathlib import Path

LANGS = ["it", "es", "fr", "de", "pt", "ja", "ko", "zh-Hans", "zh-Hant"]

# Each entry maps an English key to {lang: translation}
TRANSLATE = {
    "_auto_\\(s.lowercased().replace(' ', '_').replace('.', ''))": {
        "it": "Mostra Posizione", "es": "Mostrar Ubicación", "fr": "Afficher l'Emplacement",
        "de": "Ort zeigen", "pt": "Mostrar Localização",
        "ja": "場所を表示", "ko": "위치 보기",
        "zh-Hans": "显示位置", "zh-Hant": "顯示位置",
    },
    "App": {
        "it":"App","es":"App","fr":"App","de":"App","pt":"App",
        "ja":"アプリ","ko":"앱","zh-Hans":"应用","zh-Hant":"應用程式",
    },
    "Applications and related files will be moved to the Trash. You can restore them until the Trash is emptied.": {
        "it": "App e file correlati saranno spostati nel Cestino. Puoi ripristinarli finché il Cestino non viene svuotato.",
        "es": "Las apps y archivos relacionados se moverán a la Papelera. Puedes restaurarlos hasta vaciarla.",
        "fr": "Les apps et fichiers associés seront mis à la Corbeille. Vous pouvez les restaurer jusqu'au vidage.",
        "de": "Apps und zugehörige Dateien werden in den Papierkorb verschoben. Sie können sie wiederherstellen, bis der Papierkorb geleert wird.",
        "pt": "Apps e arquivos relacionados serão movidos para a Lixeira. Você pode restaurá-los até esvaziá-la.",
        "ja": "アプリと関連ファイルはゴミ箱に移動されます。ゴミ箱を空にするまで復元できます。",
        "ko": "앱과 관련 파일이 휴지통으로 이동됩니다. 휴지통을 비우기 전까지 복원할 수 있습니다.",
        "zh-Hans": "应用和相关文件将移至废纸篓。清空废纸篓之前可以恢复。",
        "zh-Hant": "應用程式和相關檔案將移至垃圾桶。清空垃圾桶之前可以恢復。",
    },
    "Applications and related files will be permanently deleted. This action cannot be undone.": {
        "it": "App e file correlati saranno eliminati definitivamente. Quest'azione non può essere annullata.",
        "es": "Las apps y archivos se eliminarán permanentemente. Esta acción no se puede deshacer.",
        "fr": "Les apps et fichiers seront supprimés définitivement. Cette action est irréversible.",
        "de": "Apps und Dateien werden endgültig gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
        "pt": "Apps e arquivos serão excluídos permanentemente. Esta ação não pode ser desfeita.",
        "ja": "アプリとファイルは完全に削除されます。この操作は元に戻せません。",
        "ko": "앱과 파일이 영구적으로 삭제됩니다. 이 작업은 취소할 수 없습니다.",
        "zh-Hans": "应用和文件将被永久删除。此操作无法撤消。",
        "zh-Hant": "應用程式和檔案將被永久刪除。此操作無法復原。",
    },
    "Apps you remove with Uninstally will appear here, so you can review or restore them.": {
        "it": "Le app rimosse con Uninstally appariranno qui per revisione o ripristino.",
        "es": "Las apps eliminadas con Uninstally aparecerán aquí para revisarlas o restaurarlas.",
        "fr": "Les apps supprimées avec Uninstally apparaîtront ici pour consultation ou restauration.",
        "de": "Mit Uninstally entfernte Apps erscheinen hier zur Ansicht oder Wiederherstellung.",
        "pt": "Apps removidas com Uninstally aparecerão aqui para revisão ou restauração.",
        "ja": "Uninstallyで削除したアプリがここに表示され、確認や復元ができます。",
        "ko": "Uninstally로 제거한 앱이 여기에 표시되어 검토하거나 복원할 수 있습니다.",
        "zh-Hans": "使用 Uninstally 删除的应用将显示在此处，方便查看或恢复。",
        "zh-Hant": "使用 Uninstally 刪除的應用程式將顯示在此處，方便查看或恢復。",
    },
    "Automatically remove entries older than this.": {
        "it": "Rimuovi automaticamente le voci più vecchie di questo periodo.",
        "es": "Eliminar automáticamente entradas más antiguas que esto.",
        "fr": "Supprimer automatiquement les entrées plus anciennes.",
        "de": "Ältere Einträge automatisch entfernen.",
        "pt": "Remover automaticamente entradas mais antigas que isso.",
        "ja": "これより古いエントリを自動的に削除します。",
        "ko": "이보다 오래된 항목을 자동으로 제거합니다.",
        "zh-Hans": "自动删除早于此时间的条目。",
        "zh-Hant": "自動刪除早於此時間的條目。",
    },
    "Beta": {
        "it":"Beta","es":"Beta","fr":"Bêta","de":"Beta","pt":"Beta",
        "ja":"ベータ","ko":"베타","zh-Hans":"Beta","zh-Hant":"Beta",
    },
    "Calculating storage…": {
        "it": "Calcolo dello spazio\u2026",
        "es": "Calculando almacenamiento\u2026",
        "fr": "Calcul du stockage\u2026",
        "de": "Berechne Speicher\u2026",
        "pt": "Calculando armazenamento\u2026",
        "ja": "ストレージを計算中\u2026",
        "ko": "저장소 계산 중\u2026",
        "zh-Hans": "正在计算存储空间\u2026",
        "zh-Hant": "正在計算儲存空間\u2026",
    },
    "Cask": {
        "it":"Cask","es":"Cask","fr":"Cask","de":"Cask","pt":"Cask",
        "ja":"Cask","ko":"Cask","zh-Hans":"Cask","zh-Hant":"Cask",
    },
    "Checking": {
        "it": "Verifica", "es": "Comprobando", "fr": "Vérification",
        "de": "Prüfung", "pt": "Verificando",
        "ja": "確認", "ko": "확인", "zh-Hans": "检查", "zh-Hant": "檢查",
    },
    "Collection Not Found": {
        "it": "Collezione non Trovata", "es": "Colección no Encontrada",
        "fr": "Collection Introuvable", "de": "Sammlung nicht gefunden",
        "pt": "Coleção não Encontrada", "ja": "コレクションが見つかりません",
        "ko": "컬렉션을 찾을 수 없음", "zh-Hans": "未找到收藏", "zh-Hant": "找不到收藏",
    },
    "Collections only organize apps — they never change what's installed.": {
        "it": "Le Collezioni organizzano solo le app — non cambiano ciò che è installato.",
        "es": "Las Colecciones solo organizan apps — nunca cambian lo instalado.",
        "fr": "Les Collections organisent seulement les apps — elles ne changent rien à ce qui est installé.",
        "de": "Sammlungen organisieren nur Apps — sie ändern nie, was installiert ist.",
        "pt": "Coleções apenas organizam apps — nunca alteram o que está instalado.",
        "ja": "コレクションはアプリを整理するだけで、インストール済みの内容は変更しません。",
        "ko": "컬렉션은 앱을 정리할 뿐, 설치된 내용을 변경하지 않습니다.",
        "zh-Hans": "收藏仅用于整理应用，不会更改已安装的内容。",
        "zh-Hant": "收藏僅用於整理應用程式，不會更改已安裝的內容。",
    },
    "Confirm": {
        "it":"Conferma","es":"Confirmar","fr":"Confirmer","de":"Bestätigen","pt":"Confirmar",
        "ja":"確認","ko":"확인","zh-Hans":"确认","zh-Hant":"確認",
    },
    "Couldn't mount the downloaded disk image.": {
        "it": "Impossibile montare l'immagine disco scaricata.",
        "es": "No se pudo montar la imagen de disco descargada.",
        "fr": "Impossible de monter l'image disque téléchargée.",
        "de": "Das heruntergeladene Disk-Image konnte nicht gemountet werden.",
        "pt": "Não foi possível montar a imagem de disco baixada.",
        "ja": "ダウンロードしたディスクイメージをマウントできませんでした。",
        "ko": "다운로드한 디스크 이미지를 마운트할 수 없습니다.",
        "zh-Hans": "无法挂载下载的磁盘映像。",
        "zh-Hant": "無法掛載下載的磁碟映像。",
    },
    "Couldn't read the release information from GitHub.": {
        "it": "Impossibile leggere le informazioni di rilascio da GitHub.",
        "es": "No se pudieron leer las informaciones de la versión desde GitHub.",
        "fr": "Impossible de lire les informations de version depuis GitHub.",
        "de": "Release-Informationen konnten nicht von GitHub gelesen werden.",
        "pt": "Não foi possível ler as informações de lançamento do GitHub.",
        "ja": "GitHubからリリース情報を読み取れませんでした。",
        "ko": "GitHub에서 릴리스 정보를 읽을 수 없습니다.",
        "zh-Hans": "无法从 GitHub 读取发布信息。",
        "zh-Hant": "無法從 GitHub 讀取發佈資訊。",
    },
    "Create a Collection to group and categorize apps. Add apps by dragging them onto a Collection or right-clicking an app.": {
        "it": "Crea una Collezione per raggruppare le app. Aggiungi app trascinandole su una Collezione o con clic destro.",
        "es": "Crea una Colección para agrupar apps. Añade apps arrastrándolas a una Colección o con clic derecho.",
        "fr": "Créez une Collection pour regrouper les apps. Ajoutez des apps en les glissant sur une Collection ou par clic droit.",
        "de": "Erstellen Sie eine Sammlung zum Gruppieren von Apps. Fügen Sie Apps per Drag & Drop oder Rechtsklick hinzu.",
        "pt": "Crie uma Coleção para agrupar apps. Adicione apps arrastando-as para uma Coleção ou com clique direito.",
        "ja": "コレクションを作成してアプリをグループ化します。アプリをコレクションにドラッグするか、右クリックで追加します。",
        "ko": "컬렉션을 만들어 앱을 그룹화하세요. 앱을 컬렉션으로 드래그하거나 우클릭하여 추가하세요.",
        "zh-Hans": "创建收藏以分组应用。将应用拖到收藏或右键点击应用即可添加。",
        "zh-Hant": "建立收藏以分組應用程式。將應用程式拖到收藏或右鍵點按應用程式即可新增。",
    },
    "Customize Collections…": {
        "it":"Personalizza Collezioni\u2026","es":"Personalizar Colecciones\u2026",
        "fr":"Personnaliser les Collections\u2026","de":"Sammlungen anpassen\u2026",
        "pt":"Personalizar Coleções\u2026","ja":"コレクションをカスタマイズ\u2026",
        "ko":"컬렉션 사용자 정의\u2026","zh-Hans":"自定义收藏\u2026","zh-Hant":"自訂收藏\u2026",
    },
    "Customize sidebar and Collections": {
        "it":"Personalizza barra e Collezioni","es":"Personalizar barra y Colecciones",
        "fr":"Personnaliser la barre et les Collections","de":"Seitenleiste und Sammlungen anpassen",
        "pt":"Personalizar barra e Coleções","ja":"サイドバーとコレクションをカスタマイズ",
        "ko":"사이드바 및 컬렉션 사용자 정의","zh-Hans":"自定义侧边栏和收藏",
        "zh-Hant":"自訂側邊欄和收藏",
    },
    "Duplicated Across Drives": {
        "it":"Duplicate su Più Dischi","es":"Duplicadas en Varios Discos",
        "fr":"Dupliquées sur Plusieurs Disques","de":"Auf Laufwerken dupliziert",
        "pt":"Duplicadas em Vários Discos","ja":"複数のドライブに重複",
        "ko":"여러 드라이브에 중복","zh-Hans":"跨驱动器重复","zh-Hant":"跨磁碟重複",
    },
    "Enable beta updates to choose a pre-release channel.": {
        "it":"Abilita gli aggiornamenti beta per scegliere un canale pre-release.",
        "es":"Activa las actualizaciones beta para elegir un canal prelanzamiento.",
        "fr":"Activez les mises à jour bêta pour choisir un canal préliminaire.",
        "de":"Beta-Updates aktivieren, um einen Pre-Release-Kanal zu wählen.",
        "pt":"Ative as atualizações beta para escolher um canal de pré-lançamento.",
        "ja":"ベータ版アップデートを有効にしてプレリリースチャンネルを選択します。",
        "ko":"베타 업데이트를 활성화하여 사전 출시 채널을 선택하세요.",
        "zh-Hans":"启用 Beta 更新以选择预发布通道。",
        "zh-Hant":"啟用 Beta 更新以選擇預發佈通道。",
    },
    "Enter a new name for this collection.": {
        "it":"Inserisci un nuovo nome per questa collezione.",
        "es":"Introduce un nuevo nombre para esta colección.",
        "fr":"Saisissez un nouveau nom pour cette collection.",
        "de":"Geben Sie einen neuen Namen für diese Sammlung ein.",
        "pt":"Digite um novo nome para esta coleção.",
        "ja":"このコレクションの新しい名前を入力してください。",
        "ko":"이 컬렉션의 새 이름을 입력하세요.",
        "zh-Hans":"为此收藏输入新名称。","zh-Hant":"為此收藏輸入新名稱。",
    },
    "Formula": {
        "it":"Formula","es":"Fórmula","fr":"Formule","de":"Formel","pt":"Fórmula",
        "ja":"Formula","ko":"Formula","zh-Hans":"Formula","zh-Hant":"Formula",
    },
    "GitHub": {
        "it":"GitHub","es":"GitHub","fr":"GitHub","de":"GitHub","pt":"GitHub",
        "ja":"GitHub","ko":"GitHub","zh-Hans":"GitHub","zh-Hant":"GitHub",
    },
    "GitHub rate limit reached. Please try again later.": {
        "it":"Limite di richieste GitHub raggiunto. Riprova più tardi.",
        "es":"Límite de solicitudes de GitHub alcanzado. Inténtalo más tarde.",
        "fr":"Limite de requêtes GitHub atteinte. Réessayez plus tard.",
        "de":"GitHub-Ratenlimit erreicht. Bitte versuchen Sie es später erneut.",
        "pt":"Limite de requisições do GitHub atingido. Tente novamente mais tarde.",
        "ja":"GitHubのレート制限に達しました。後でもう一度お試しください。",
        "ko":"GitHub 요청 제한에 도달했습니다. 나중에 다시 시도하세요.",
        "zh-Hans":"GitHub 速率限制已达上限，请稍后重试。",
        "zh-Hant":"GitHub 速率限制已達上限，請稍後重試。",
    },
    "Hidden sections stay available — they're only removed from the sidebar.": {
        "it":"Le sezioni nascoste restano disponibili — sono solo rimosse dalla barra laterale.",
        "es":"Las secciones ocultas siguen disponibles — solo se eliminan de la barra lateral.",
        "fr":"Les sections masquées restent disponibles — elles sont seulement retirées de la barre.",
        "de":"Ausgeblendete Bereiche bleiben verfügbar — sie werden nur aus der Seitenleiste entfernt.",
        "pt":"Seções ocultas permanecem disponíveis — são apenas removidas da barra lateral.",
        "ja":"非表示のセクションも引き続き利用可能です — サイドバーから削除されるだけです。",
        "ko":"숨겨진 섹션도 계속 사용할 수 있습니다 — 사이드바에서만 제거됩니다.",
        "zh-Hans":"隐藏的部分仍然可用，只是从侧边栏中移除。",
        "zh-Hant":"隱藏的部分仍然可用，只是從側邊欄中移除。",
    },
    "Homebrew": {
        "it":"Homebrew","es":"Homebrew","fr":"Homebrew","de":"Homebrew","pt":"Homebrew",
        "ja":"Homebrew","ko":"Homebrew","zh-Hans":"Homebrew","zh-Hant":"Homebrew",
    },
    "Include pre-release builds from the selected channel.": {
        "it":"Includi build pre-release dal canale selezionato.",
        "es":"Incluir builds prelanzamiento del canal seleccionado.",
        "fr":"Inclure les builds préliminaires du canal sélectionné.",
        "de":"Pre-Release-Builds aus dem gewählten Kanal einbeziehen.",
        "pt":"Incluir builds de pré-lançamento do canal selecionado.",
        "ja":"選択したチャンネルのプレリリースビルドを含めます。",
        "ko":"선택한 채널의 사전 출시 빌드를 포함합니다.",
        "zh-Hans":"包含所选通道的预发布版本。",
        "zh-Hant":"包含所選通道的預發佈版本。",
    },
    "Install Homebrew from brew.sh to manage command-line packages and casks here.": {
        "it":"Installa Homebrew da brew.sh per gestire pacchetti e casks da riga di comando.",
        "es":"Instala Homebrew desde brew.sh para gestionar paquetes y casks aquí.",
        "fr":"Installez Homebrew depuis brew.sh pour gérer les paquets et casks ici.",
        "de":"Installieren Sie Homebrew von brew.sh, um Pakete und Casks hier zu verwalten.",
        "pt":"Instale o Homebrew de brew.sh para gerenciar pacotes e casks aqui.",
        "ja":"brew.shからHomebrewをインストールして、コマンドラインパッケージとcaskをここで管理します。",
        "ko":"brew.sh에서 Homebrew를 설치하여 명령줄 패키지와 cask를 여기서 관리하세요.",
        "zh-Hans":"从 brew.sh 安装 Homebrew 以在此管理命令行软件包和 casks。",
        "zh-Hant":"從 brew.sh 安裝 Homebrew 以在此管理命令列軟體套件和 casks。",
    },
    "Item still present after deletion": {
        "it":"Elemento ancora presente dopo l'eliminazione",
        "es":"El elemento sigue presente después de la eliminación",
        "fr":"Élément toujours présent après suppression",
        "de":"Element nach Löschung noch vorhanden",
        "pt":"Item ainda presente após exclusão",
        "ja":"削除後もアイテムが存在します",
        "ko":"삭제 후에도 항목이 남아 있습니다",
        "zh-Hans":"删除后项目仍然存在",
        "zh-Hant":"刪除後項目仍然存在",
    },
    "Layout": {
        "it":"Layout","es":"Diseño","fr":"Disposition","de":"Layout","pt":"Layout",
        "ja":"レイアウト","ko":"레이아웃","zh-Hans":"布局","zh-Hant":"佈局",
    },
    "No orphaned files found": {
        "it":"Nessun file orfano trovato",
        "es":"No se encontraron archivos huérfanos",
        "fr":"Aucun fichier orphelin trouvé",
        "de":"Keine verwaisten Dateien gefunden",
        "pt":"Nenhum arquivo órfão encontrado",
        "ja":"孤立ファイルは見つかりませんでした",
        "ko":"분리된 파일을 찾을 수 없습니다",
        "zh-Hans":"未找到孤立文件",
        "zh-Hant":"找不到孤立檔案",
    },
    "OK": {
        "it":"OK","es":"Aceptar","fr":"OK","de":"OK","pt":"OK",
        "ja":"OK","ko":"확인","zh-Hans":"确定","zh-Hant":"確定",
    },
    "Off": {
        "it":"Spento","es":"Apagado","fr":"Désactivé","de":"Aus","pt":"Desligado",
        "ja":"オフ","ko":"끔","zh-Hans":"关闭","zh-Hant":"關閉",
    },
    "On": {
        "it":"Acceso","es":"Encendido","fr":"Activé","de":"Ein","pt":"Ligado",
        "ja":"オン","ko":"켬","zh-Hans":"开启","zh-Hant":"開啟",
    },
    "Open the Leftover Scanner to review and remove orphaned files": {
        "it":"Apri la Scansione Residui per esaminare e rimuovere i file orfani",
        "es":"Abre el Escáner de Residuos para revisar y eliminar archivos huérfanos",
        "fr":"Ouvrez le Scanner de Résidus pour consulter et supprimer les fichiers orphelins",
        "de":"Öffnen Sie den Restescanner, um verwaiste Dateien zu prüfen und zu entfernen",
        "pt":"Abra o Scanner de Resíduos para revisar e remover arquivos órfãos",
        "ja":"残存スキャナーを開いて孤立ファイルを確認・削除します",
        "ko":"잔여물 스캐너를 열어 분리된 파일을 검토하고 제거하세요",
        "zh-Hans":"打开残留扫描器以查看和删除孤立文件",
        "zh-Hant":"開啟殘留掃描器以查看和刪除孤立檔案",
    },
    "Organize the Applications sidebar and your Collections.": {
        "it":"Organizza la barra Applicazioni e le tue Collezioni.",
        "es":"Organiza la barra de Aplicaciones y tus Colecciones.",
        "fr":"Organisez la barre Applications et vos Collections.",
        "de":"Organisieren Sie die Anwendungsseitenleiste und Ihre Sammlungen.",
        "pt":"Organize a barra lateral de Aplicativos e suas Coleções.",
        "ja":"アプリケーションサイドバーとコレクションを整理します。",
        "ko":"응용 프로그램 사이드바와 컬렉션을 정리하세요.",
        "zh-Hans":"整理应用程序侧边栏和您的收藏。",
        "zh-Hant":"整理應用程式側邊欄和您的收藏。",
    },
    "Outside every approved location": {
        "it":"Fuori da ogni posizione approvata",
        "es":"Fuera de toda ubicación aprobada",
        "fr":"En dehors de tout emplacement approuvé",
        "de":"Außerhalb aller genehmigten Orte",
        "pt":"Fora de todos os locais aprovados",
        "ja":"承認された場所の外です",
        "ko":"승인된 위치 외부",
        "zh-Hans":"不在任何已批准的位置内",
        "zh-Hant":"不在任何已批准的位置內",
    },
    "Path no longer exists": {
        "it":"Il percorso non esiste più",
        "es":"La ruta ya no existe",
        "fr":"Le chemin n'existe plus",
        "de":"Pfad existiert nicht mehr",
        "pt":"O caminho não existe mais",
        "ja":"パスはもう存在しません",
        "ko":"경로가 더 이상 존재하지 않습니다",
        "zh-Hans":"路径不再存在",
        "zh-Hant":"路徑不再存在",
    },
    "Pin to top": {
        "it":"Fissa in alto","es":"Fijar arriba","fr":"Épingler en haut",
        "de":"Oben anheften","pt":"Fixar no topo",
        "ja":"上部に固定","ko":"상단에 고정",
        "zh-Hans":"置顶","zh-Hant":"置頂",
    },
    "Protected system location": {
        "it":"Posizione di sistema protetta",
        "es":"Ubicación de sistema protegida",
        "fr":"Emplacement système protégé",
        "de":"Geschützter Systemort",
        "pt":"Localização de sistema protegida",
        "ja":"保護されたシステムの場所",
        "ko":"보호된 시스템 위치",
        "zh-Hans":"受保护的系统位置",
        "zh-Hant":"受保護的系統位置",
    },
    "Recovered": {
        "it":"Recuperato","es":"Recuperado","fr":"Récupéré",
        "de":"Wiederhergestellt","pt":"Recuperado",
        "ja":"回復済み","ko":"복구됨",
        "zh-Hans":"已恢复","zh-Hant":"已恢復",
    },
    "Refreshing": {
        "it":"Aggiornamento","es":"Actualizando","fr":"Actualisation",
        "de":"Aktualisierung","pt":"Atualizando",
        "ja":"更新中","ko":"새로고침 중",
        "zh-Hans":"刷新中","zh-Hant":"重新整理中",
    },
    "Refuses to delete an approved root directory": {
        "it":"Rifiutata l'eliminazione di una directory root approvata",
        "es":"Se rechaza eliminar un directorio raíz aprobado",
        "fr":"Refus de supprimer un répertoire racine approuvé",
        "de":"Löschen eines genehmigten Stammverzeichnisses verweigert",
        "pt":"Recusa-se a excluir um diretório raiz aprovado",
        "ja":"承認されたルートディレクトリの削除は拒否されました",
        "ko":"승인된 루트 디렉토리 삭제가 거부되었습니다",
        "zh-Hans":"拒绝删除已批准的根目录",
        "zh-Hant":"拒絕刪除已批准的根目錄",
    },
    "Remove every entry from the uninstall history.": {
        "it":"Rimuovi ogni voce dalla cronologia disinstallazioni.",
        "es":"Eliminar cada entrada del historial de desinstalaciones.",
        "fr":"Supprimer chaque entrée de l'historique de désinstallation.",
        "de":"Jeden Eintrag aus dem Deinstallationsverlauf entfernen.",
        "pt":"Remover todas as entradas do histórico de desinstalação.",
        "ja":"アンインストール履歴からすべてのエントリを削除します。",
        "ko":"제거 기록에서 모든 항목을 삭제합니다.",
        "zh-Hans":"从卸载历史中删除所有条目。",
        "zh-Hant":"從解除安裝歷史中刪除所有條目。",
    },
    "Removes files immediately and cannot be undone.": {
        "it":"Rimuove i file immediatamente e non può essere annullato.",
        "es":"Elimina archivos inmediatamente y no se puede deshacer.",
        "fr":"Supprime les fichiers immédiatement et ne peut être annulé.",
        "de":"Entfernt Dateien sofort und kann nicht rückgängig gemacht werden.",
        "pt":"Remove arquivos imediatamente e não pode ser desfeito.",
        "ja":"ファイルを即座に削除し、元に戻せません。",
        "ko":"파일을 즉시 삭제하며 되돌릴 수 없습니다.",
        "zh-Hans":"立即删除文件，无法撤消。",
        "zh-Hant":"立即刪除檔案，無法復原。",
    },
    "Restore Uninstally's settings, sidebar layout and collections to their defaults. Takes effect on next launch.": {
        "it":"Ripristina impostazioni, layout barra e collezioni ai valori predefiniti. Effettivo al prossimo avvio.",
        "es":"Restaurar ajustes, barra lateral y colecciones a sus valores predeterminados. Efectivo en el próximo inicio.",
        "fr":"Restaurer les paramètres, la barre latérale et les collections par défaut. Prend effet au prochain lancement.",
        "de":"Stellt Einstellungen, Seitenleiste und Sammlungen auf Standardwerte zurück. Wird beim nächsten Start wirksam.",
        "pt":"Restaurar definições, barra lateral e coleções aos padrões. Entra em vigor no próximo início.",
        "ja":"設定、サイドバーレイアウト、コレクションをデフォルトに戻します。次回起動時に反映されます。",
        "ko":"설정, 사이드바 레이아웃 및 컬렉션을 기본값으로 복원합니다. 다음 실행 시 적용됩니다.",
        "zh-Hans":"将 Uninstally 的设置、侧边栏布局和收藏恢复为默认值，下次启动时生效。",
        "zh-Hant":"將 Uninstally 的設定、側邊欄佈局和收藏恢復為預設值，下次啟動時生效。",
    },
    "Safer option. Files can be recovered from the Trash.": {
        "it":"Opzione più sicura. I file possono essere recuperati dal Cestino.",
        "es":"Opción más segura. Los archivos se pueden recuperar de la Papelera.",
        "fr":"Option plus sûre. Les fichiers peuvent être récupérés de la Corbeille.",
        "de":"Sicherere Option. Dateien können aus dem Papierkorb wiederhergestellt werden.",
        "pt":"Opção mais segura. Os arquivos podem ser recuperados da Lixeira.",
        "ja":"より安全なオプションです。ファイルはゴミ箱から復元できます。",
        "ko":"더 안전한 옵션입니다. 파일을 휴지통에서 복원할 수 있습니다.",
        "zh-Hans":"更安全的选项。文件可以从废纸篓恢复。",
        "zh-Hant":"更安全的選項。檔案可以從垃圾桶恢復。",
    },
    "Scanning application…": {
        "it":"Scansione dell'applicazione\u2026",
        "es":"Escaneando aplicación\u2026",
        "fr":"Analyse de l'application\u2026",
        "de":"Anwendung wird gescannt\u2026",
        "pt":"Escaneando aplicativo\u2026",
        "ja":"アプリケーションをスキャン中\u2026",
        "ko":"응용 프로그램 스캔 중\u2026",
        "zh-Hans":"正在扫描应用程序\u2026",
        "zh-Hant":"正在掃描應用程式\u2026",
    },
    "Scanning for leftovers…": {
        "it":"Ricerca residui in corso\u2026",
        "es":"Buscando residuos\u2026",
        "fr":"Recherche de résidus\u2026",
        "de":"Suche nach Resten\u2026",
        "pt":"Procurando resíduos\u2026",
        "ja":"残存ファイルを検索中\u2026",
        "ko":"잔여물 검색 중\u2026",
        "zh-Hans":"正在扫描残留文件\u2026",
        "zh-Hant":"正在掃描殘留檔案\u2026",
    },
    "Scanning for orphaned files…": {
        "it":"Scansione file orfani in corso\u2026",
        "es":"Escaneando archivos huérfanos\u2026",
        "fr":"Analyse des fichiers orphelins en cours\u2026",
        "de":"Suche nach verwaisten Dateien\u2026",
        "pt":"Escaneando arquivos órfãos\u2026",
        "ja":"孤立ファイルをスキャン中\u2026",
        "ko":"분리된 파일 스캔 중\u2026",
        "zh-Hans":"正在扫描孤立文件\u2026",
        "zh-Hant":"正在掃描孤立檔案\u2026",
    },
    "Searching containers, caches and preferences…": {
        "it":"Ricerca container, cache e preferenze\u2026",
        "es":"Buscando contenedores, cachés y preferencias\u2026",
        "fr":"Recherche de conteneurs, caches et préférences\u2026",
        "de":"Suche nach Containern, Caches und Einstellungen\u2026",
        "pt":"Procurando contêineres, caches e preferências\u2026",
        "ja":"コンテナ、キャッシュ、設定を検索中\u2026",
        "ko":"컨테이너, 캐시, 환경설정 검색 중\u2026",
        "zh-Hans":"正在搜索容器、缓存和偏好设置\u2026",
        "zh-Hant":"正在搜尋容器、快取和偏好設定\u2026",
    },
    "Searching login items, launch agents and services…": {
        "it":"Ricerca elementi login, agenti di avvio e servizi\u2026",
        "es":"Buscando ítems de inicio, agentes y servicios\u2026",
        "fr":"Recherche d'éléments d'ouverture, agents et services\u2026",
        "de":"Suche nach Anmeldeobjekten, Launch-Agents und Diensten\u2026",
        "pt":"Procurando itens de login, agentes e serviços\u2026",
        "ja":"ログイン項目、起動エージェント、サービスを検索中\u2026",
        "ko":"로그인 항목, 시작 에이전트, 서비스 검색 중\u2026",
        "zh-Hans":"正在搜索登录项、启动代理和服务\u2026",
        "zh-Hant":"正在搜尋登入項目、啟動代理和服務\u2026",
    },
    "Settings sections": {
        "it":"Sezioni Impostazioni","es":"Secciones de Ajustes",
        "fr":"Sections Préférences","de":"Einstellungsbereiche",
        "pt":"Seções de Definições","ja":"設定セクション",
        "ko":"설정 섹션","zh-Hans":"设置部分","zh-Hant":"設定區段",
    },
    "Show or hide in the sidebar": {
        "it":"Mostra o nascondi nella barra laterale",
        "es":"Mostrar u ocultar en la barra lateral",
        "fr":"Afficher ou masquer dans la barre latérale",
        "de":"In der Seitenleiste anzeigen oder ausblenden",
        "pt":"Mostrar ou ocultar na barra lateral",
        "ja":"サイドバーで表示/非表示",
        "ko":"사이드바에서 표시/숨기기",
        "zh-Hans":"在侧边栏中显示或隐藏",
        "zh-Hant":"在側邊欄中顯示或隱藏",
    },
    "Source language — translation ready": {
        "it":"Lingua sorgente — traduzione pronta",
        "es":"Idioma fuente — traducción lista",
        "fr":"Langue source — traduction prête",
        "de":"Quellsprache — Übersetzung bereit",
        "pt":"Idioma de origem — tradução pronta",
        "ja":"ソース言語 — 翻訳準備完了",
        "ko":"소스 언어 — 번역 준비 완료",
        "zh-Hans":"源语言 — 翻译就绪",
        "zh-Hant":"來源語言 — 翻譯就緒",
    },
    "Switch between grid and list": {
        "it":"Alterna tra griglia e lista",
        "es":"Alternar entre cuadrícula y lista",
        "fr":"Basculer entre grille et liste",
        "de":"Zwischen Raster und Liste wechseln",
        "pt":"Alternar entre grade e lista",
        "ja":"グリッドとリストを切り替え",
        "ko":"그리드와 목록 간 전환",
        "zh-Hans":"在网格和列表之间切换",
        "zh-Hant":"在網格和列表之間切換",
    },
    "The application needs to restart to apply the selected language.": {
        "it":"L'applicazione deve essere riavviata per applicare la lingua selezionata.",
        "es":"La aplicación debe reiniciarse para aplicar el idioma seleccionado.",
        "fr":"L'application doit redémarrer pour appliquer la langue sélectionnée.",
        "de":"Die Anwendung muss neu gestartet werden, um die gewählte Sprache anzuwenden.",
        "pt":"O aplicativo precisa ser reiniciado para aplicar o idioma selecionado.",
        "ja":"選択した言語を適用するにはアプリケーションを再起動する必要があります。",
        "ko":"선택한 언어를 적용하려면 응용 프로그램을 다시 시작해야 합니다.",
        "zh-Hans":"应用程序需要重启才能应用所选语言。",
        "zh-Hant":"應用程式需要重新啟動才能套用所選語言。",
    },
    "The cleanest way to completely remove apps and every file they leave behind.": {
        "it":"Il modo più pulito per rimuovere completamente le app e tutti i file che lasciano.",
        "es":"La forma más limpia de eliminar completamente las apps y todos los archivos que dejan.",
        "fr":"La façon la plus propre de supprimer complètement les apps et tous les fichiers qu'elles laissent.",
        "de":"Der sauberste Weg, Apps und alle zurückbleibenden Dateien vollständig zu entfernen.",
        "pt":"A maneira mais limpa de remover completamente apps e todos os arquivos que elas deixam.",
        "ja":"アプリとそれが残すすべてのファイルを完全に削除する最もクリーンな方法です。",
        "ko":"앱과 앱이 남기는 모든 파일을 완전히 제거하는 가장 깔끔한 방법입니다.",
        "zh-Hans":"最干净的方式，彻底删除应用及其留下的所有文件。",
        "zh-Hant":"最乾淨的方式，徹底刪除應用程式及其留下的所有檔案。",
    },
    "The disk image didn't contain Uninstally.": {
        "it":"L'immagine disco non conteneva Uninstally.",
        "es":"La imagen de disco no contenía Uninstally.",
        "fr":"L'image disque ne contenait pas Uninstally.",
        "de":"Das Disk-Image enthielt Uninstally nicht.",
        "pt":"A imagem de disco não continha o Uninstally.",
        "ja":"ディスクイメージにUninstallyが含まれていませんでした。",
        "ko":"디스크 이미지에 Uninstally가 포함되어 있지 않습니다.",
        "zh-Hans":"磁盘映像中未包含 Uninstally。",
        "zh-Hant":"磁碟映像中未包含 Uninstally。",
    },
    "The latest release has no downloadable DMG.": {
        "it":"L'ultima release non ha un DMG scaricabile.",
        "es":"La última versión no tiene un DMG descargable.",
        "fr":"La dernière version n'a pas de DMG téléchargeable.",
        "de":"Die neueste Version hat kein herunterladbares DMG.",
        "pt":"A versão mais recente não tem um DMG para download.",
        "ja":"最新リリースにダウンロード可能なDMGがありません。",
        "ko":"최신 릴리스에 다운로드 가능한 DMG가 없습니다.",
        "zh-Hans":"最新版本没有可下载的 DMG。",
        "zh-Hant":"最新版本沒有可下載的 DMG。",
    },
    "The selected apps and their files will be moved to the Trash.": {
        "it":"Le app selezionate e i loro file saranno spostati nel Cestino.",
        "es":"Las apps seleccionadas y sus archivos se moverán a la Papelera.",
        "fr":"Les apps sélectionnées et leurs fichiers seront mis à la Corbeille.",
        "de":"Die ausgewählten Apps und ihre Dateien werden in den Papierkorb verschoben.",
        "pt":"Os apps selecionados e seus arquivos serão movidos para a Lixeira.",
        "ja":"選択したアプリとそのファイルはゴミ箱に移動されます。",
        "ko":"선택한 앱과 해당 파일이 휴지통으로 이동됩니다.",
        "zh-Hans":"所选应用及其文件将移至废纸篓。",
        "zh-Hant":"所選應用程式及其檔案將移至垃圾桶。",
    },
    "The update came from an untrusted source and was blocked.": {
        "it":"L'aggiornamento proviene da una fonte non attendibile ed è stato bloccato.",
        "es":"La actualización provino de una fuente no confiable y fue bloqueada.",
        "fr":"La mise à jour provenait d'une source non fiable et a été bloquée.",
        "de":"Das Update stammte von einer nicht vertrauenswürdigen Quelle und wurde blockiert.",
        "pt":"A atualização veio de uma fonte não confiável e foi bloqueada.",
        "ja":"更新は信頼できないソースからのもので、ブロックされました。",
        "ko":"업데이트가 신뢰할 수 없는 출처에서 와서 차단되었습니다.",
        "zh-Hans":"更新来自不受信任的来源，已被阻止。",
        "zh-Hant":"更新來自不受信任的來源，已被阻止。",
    },
    "The update was cancelled.": {
        "it":"L'aggiornamento è stato annullato.",
        "es":"La actualización fue cancelada.",
        "fr":"La mise à jour a été annulée.",
        "de":"Das Update wurde abgebrochen.",
        "pt":"A atualização foi cancelada.",
        "ja":"更新はキャンセルされました。",
        "ko":"업데이트가 취소되었습니다.",
        "zh-Hans":"更新已取消。",
        "zh-Hant":"更新已取消。",
    },
    "These items may be used by other software. Review them before removing — deselect any you want to keep.": {
        "it":"Questi elementi potrebbero essere usati da altri software. Esaminali prima di rimuovere — deseleziona quelli da conservare.",
        "es":"Estos elementos pueden ser usados por otro software. Revísalos antes de eliminar — deselecciona los que quieras conservar.",
        "fr":"Ces éléments peuvent être utilisés par d'autres logiciels. Vérifiez-les avant de supprimer — désélectionnez ceux à conserver.",
        "de":"Diese Elemente könnten von anderer Software verwendet werden. Überprüfen Sie sie vor dem Entfernen — deaktivieren Sie die, die Sie behalten möchten.",
        "pt":"Estes itens podem ser usados por outros softwares. Revise-os antes de remover — desmarque os que deseja manter.",
        "ja":"これらの項目は他のソフトウェアで使用されている可能性があります。削除前に確認し、保持するものは選択解除してください。",
        "ko":"이 항목은 다른 소프트웨어에서 사용될 수 있습니다. 제거하기 전에 검토하고 유지할 항목은 선택 해제하세요.",
        "zh-Hans":"这些项目可能被其他软件使用。删除前请检查，取消选择要保留的项目。",
        "zh-Hant":"這些項目可能被其他軟體使用。刪除前請檢查，取消選擇要保留的項目。",
    },
    "This install appears to be broken or incomplete": {
        "it":"Questa installazione sembra danneggiata o incompleta",
        "es":"Esta instalación parece dañada o incompleta",
        "fr":"Cette installation semble endommagée ou incomplète",
        "de":"Diese Installation scheint beschädigt oder unvollständig zu sein",
        "pt":"Esta instalação parece estar danificada ou incompleta",
        "ja":"このインストールは破損しているか不完全なようです",
        "ko":"이 설치가 손상되었거나 불완전한 것 같습니다",
        "zh-Hans":"此安装似乎已损坏或不完整",
        "zh-Hant":"此安裝似乎已損壞或不完整",
    },
    "This permanently removes every entry from the history. It does not affect files already in the Trash.": {
        "it":"Rimuove definitivamente ogni voce dalla cronologia. Non influisce sui file già nel Cestino.",
        "es":"Elimina permanentemente cada entrada del historial. No afecta a los archivos ya en la Papelera.",
        "fr":"Supprime définitivement chaque entrée de l'historique. N'affecte pas les fichiers déjà dans la Corbeille.",
        "de":"Entfernt jeden Eintrag dauerhaft aus dem Verlauf. Bereits im Papierkorb befindliche Dateien sind nicht betroffen.",
        "pt":"Remove permanentemente todas as entradas do histórico. Não afeta arquivos já na Lixeira.",
        "ja":"履歴からすべてのエントリを完全に削除します。既にゴミ箱にあるファイルには影響しません。",
        "ko":"기록에서 모든 항목을 영구적으로 삭제합니다. 이미 휴지통에 있는 파일에는 영향을 주지 않습니다.",
        "zh-Hans":"从历史中永久删除所有条目。不影响已在废纸篓中的文件。",
        "zh-Hant":"從歷史中永久刪除所有條目。不影響已在垃圾桶中的檔案。",
    },
    "This permanently removes every entry. It does not affect files already in the Trash.": {
        "it":"Rimuove definitivamente ogni voce. Non influisce sui file già nel Cestino.",
        "es":"Elimina permanentemente cada entrada. No afecta a los archivos ya en la Papelera.",
        "fr":"Supprime définitivement chaque entrée. N'affecte pas les fichiers déjà dans la Corbeille.",
        "de":"Entfernt jeden Eintrag dauerhaft. Bereits im Papierkorb befindliche Dateien sind nicht betroffen.",
        "pt":"Remove permanentemente todas as entradas. Não afeta arquivos já na Lixeira.",
        "ja":"すべてのエントリを完全に削除します。既にゴミ箱にあるファイルには影響しません。",
        "ko":"모든 항목을 영구적으로 삭제합니다. 이미 휴지통에 있는 파일에는 영향을 주지 않습니다.",
        "zh-Hans":"永久删除所有条目。不影响已在废纸篓中的文件。",
        "zh-Hant":"永久刪除所有條目。不影響已在垃圾桶中的檔案。",
    },
    "This simulation has not deleted any files.": {
        "it":"Questa simulazione non ha eliminato alcun file.",
        "es":"Esta simulación no ha eliminado ningún archivo.",
        "fr":"Cette simulation n'a supprimé aucun fichier.",
        "de":"Diese Simulation hat keine Dateien gelöscht.",
        "pt":"Esta simulação não excluiu nenhum arquivo.",
        "ja":"このシミュレーションではファイルは削除されていません。",
        "ko":"이 시뮬레이션에서 파일이 삭제되지 않았습니다.",
        "zh-Hans":"此模拟尚未删除任何文件。",
        "zh-Hant":"此模擬尚未刪除任何檔案。",
    },
    "This will permanently delete the selected apps. This action cannot be undone.": {
        "it":"Le app selezionate saranno eliminate definitivamente. Quest'azione non può essere annullata.",
        "es":"Esto eliminará permanentemente las apps seleccionadas. Esta acción no se puede deshacer.",
        "fr":"Cela supprimera définitivement les apps sélectionnées. Cette action est irréversible.",
        "de":"Die ausgewählten Apps werden endgültig gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
        "pt":"Isso excluirá permanentemente os apps selecionados. Esta ação não pode ser desfeita.",
        "ja":"選択したアプリは完全に削除されます。この操作は元に戻せません。",
        "ko":"선택한 앱이 영구적으로 삭제됩니다. 이 작업은 취소할 수 없습니다.",
        "zh-Hans":"这将永久删除所选应用。此操作无法撤消。",
        "zh-Hant":"這將永久刪除所選應用程式。此操作無法復原。",
    },
    "This window will close automatically.": {
        "it":"Questa finestra si chiuderà automaticamente.",
        "es":"Esta ventana se cerrará automáticamente.",
        "fr":"Cette fenêtre se fermera automatiquement.",
        "de":"Dieses Fenster schließt automatisch.",
        "pt":"Esta janela fechará automaticamente.",
        "ja":"このウィンドウは自動的に閉じます。",
        "ko":"이 창은 자동으로 닫힙니다.",
        "zh-Hans":"此窗口将自动关闭。",
        "zh-Hant":"此視窗將自動關閉。",
    },
    "Too close to a root directory": {
        "it":"Troppo vicino a una directory root",
        "es":"Demasiado cerca de un directorio raíz",
        "fr":"Trop proche d'un répertoire racine",
        "de":"Zu nah an einem Stammverzeichnis",
        "pt":"Muito próximo de um diretório raiz",
        "ja":"ルートディレクトリに近すぎます",
        "ko":"루트 디렉토리에 너무 가깝습니다",
        "zh-Hans":"太接近根目录",
        "zh-Hant":"太接近根目錄",
    },
    "Uninstally matches files by bundle identifier — not just by name — across every Library location, so nothing gets missed and nothing unrelated gets touched.": {
        "it":"Uninstally abbina i file per identificatore bundle — non solo per nome — in ogni posizione Libreria, così nulla viene tralasciato e nulla di estraneo viene toccato.",
        "es":"Uninstally empareja archivos por identificador de bundle — no solo por nombre — en cada ubicación de la Biblioteca, para que nada se pierda y nada no relacionado se toque.",
        "fr":"Uninstally fait correspondre les fichiers par identifiant de bundle — pas seulement par nom — dans chaque emplacement Bibliothèque, pour ne rien manquer et ne rien toucher d'inutile.",
        "de":"Uninstally gleicht Dateien anhand der Bundle-ID ab — nicht nur nach Namen — an jedem Bibliotheksort, sodass nichts übersehen und nichts Unbeteiligtes berührt wird.",
        "pt":"Uninstally combina arquivos por identificador de bundle — não apenas por nome — em cada local da Biblioteca, para que nada seja perdido e nada não relacionado seja tocado.",
        "ja":"Uninstallyはバンドル識別子でファイルを照合します — 名前だけでなく — すべてのライブラリの場所で、見落としがなく、無関係なものには触れません。",
        "ko":"Uninstally는 번들 식별자로 파일을 일치시킵니다 — 이름만이 아니라 — 모든 라이브러리 위치에서, 놓치는 것이 없고 관련 없는 것은 건드리지 않습니다.",
        "zh-Hans":"Uninstally 通过 Bundle 标识符匹配文件 — 而不仅仅是名称 — 在每个资源库位置，确保不遗漏任何内容，也不触及无关内容。",
        "zh-Hant":"Uninstally 透過 Bundle 識別碼比對檔案 — 而不僅僅是名稱 — 在每個資源庫位置，確保不遺漏任何內容，也不觸及無關內容。",
    },
    "Uninstally simulated each app. Nothing has been deleted.": {
        "it":"Uninstally ha simulato ogni app. Nulla è stato eliminato.",
        "es":"Uninstally simuló cada app. No se ha eliminado nada.",
        "fr":"Uninstally a simulé chaque app. Rien n'a été supprimé.",
        "de":"Uninstally hat jede App simuliert. Es wurde nichts gelöscht.",
        "pt":"Uninstally simulou cada app. Nada foi excluído.",
        "ja":"Uninstallyは各アプリをシミュレートしました。何も削除されていません。",
        "ko":"Uninstally가 각 앱을 시뮬레이션했습니다. 아무것도 삭제되지 않았습니다.",
        "zh-Hans":"Uninstally 已模拟每个应用。尚未删除任何内容。",
        "zh-Hant":"Uninstally 已模擬每個應用程式。尚未刪除任何內容。",
    },
    "Unpin from top": {
        "it":"Rimuovi dall'alto","es":"Desfijar","fr":"Désépingler",
        "de":"Anheftung aufheben","pt":"Desafixar",
        "ja":"固定解除","ko":"고정 해제",
        "zh-Hans":"取消置顶","zh-Hant":"取消置頂",
    },
    "Updates are only downloaded from the official Uninstally repository on GitHub and verified before installation.": {
        "it":"Gli aggiornamenti sono scaricati solo dal repository ufficiale Uninstally su GitHub e verificati prima dell'installazione.",
        "es":"Las actualizaciones se descargan solo del repositorio oficial de Uninstally en GitHub y se verifican antes de la instalación.",
        "fr":"Les mises à jour sont téléchargées uniquement depuis le dépôt officiel Uninstally sur GitHub et vérifiées avant installation.",
        "de":"Updates werden nur aus dem offiziellen Uninstally-Repository auf GitHub heruntergeladen und vor der Installation überprüft.",
        "pt":"As atualizações são baixadas apenas do repositório oficial do Uninstally no GitHub e verificadas antes da instalação.",
        "ja":"更新はGitHubの公式Uninstallyリポジトリからのみダウンロードされ、インストール前に検証されます。",
        "ko":"업데이트는 GitHub의 공식 Uninstally 리포지토리에서만 다운로드되며 설치 전에 확인됩니다.",
        "zh-Hans":"更新仅从 GitHub 上的官方 Uninstally 仓库下载，并在安装前进行验证。",
        "zh-Hant":"更新僅從 GitHub 上的官方 Uninstally 倉庫下載，並在安裝前進行驗證。",
    },
    "Validating every path…": {
        "it":"Convalida di ogni percorso\u2026",
        "es":"Validando cada ruta\u2026",
        "fr":"Validation de chaque chemin\u2026",
        "de":"Validiere jeden Pfad\u2026",
        "pt":"Validando cada caminho\u2026",
        "ja":"すべてのパスを検証中\u2026",
        "ko":"모든 경로 확인 중\u2026",
        "zh-Hans":"正在验证每个路径\u2026",
        "zh-Hant":"正在驗證每個路徑\u2026",
    },
    "Volume": {
        "it":"Volume","es":"Volumen","fr":"Volume","de":"Volume","pt":"Volume",
        "ja":"ボリューム","ko":"볼륨","zh-Hans":"卷","zh-Hant":"卷",
    },
    "You review everything before it's removed. Files go to the Trash where possible, and admin actions ask for permission only when needed.": {
        "it":"Esamini tutto prima della rimozione. I file vanno nel Cestino quando possibile, e le azioni admin richiedono il permesso solo quando necessario.",
        "es":"Revisas todo antes de eliminarlo. Los archivos van a la Papelera cuando es posible, y las acciones de administrador piden permiso solo cuando es necesario.",
        "fr":"Vous vérifiez tout avant suppression. Les fichiers vont à la Corbeille quand c'est possible, et les actions admin ne demandent l'autorisation que si nécessaire.",
        "de":"Sie überprüfen alles vor dem Entfernen. Dateien werden wenn möglich in den Papierkorb verschoben, und Admin-Aktionen fragen nur bei Bedarf nach Erlaubnis.",
        "pt":"Você revisa tudo antes de remover. Os arquivos vão para a Lixeira quando possível, e as ações de administrador pedem permissão apenas quando necessário.",
        "ja":"削除前にすべてを確認します。可能な場合はファイルをゴミ箱に移動し、管理者権限が必要な場合のみ許可を求めます。",
        "ko":"제거하기 전에 모든 것을 검토합니다. 가능하면 파일을 휴지통으로 보내고, 관리자 작업은 필요할 때만 권한을 요청합니다.",
        "zh-Hans":"删除前您会检查所有内容。文件尽可能放入废纸篓，管理员操作仅在必要时请求权限。",
        "zh-Hant":"刪除前您會檢查所有內容。檔案盡可能放入垃圾桶，管理員操作僅在必要時請求權限。",
    },
    "Your Mac is tidy — no orphaned files from uninstalled apps were detected.": {
        "it":"Il tuo Mac è pulito — nessun file orfano da app disinstallate è stato rilevato.",
        "es":"Tu Mac está limpio — no se detectaron archivos huérfanos de apps desinstaladas.",
        "fr":"Votre Mac est propre — aucun fichier orphelin d'apps désinstallées n'a été détecté.",
        "de":"Ihr Mac ist aufgeräumt — es wurden keine verwaisten Dateien von deinstallierten Apps erkannt.",
        "pt":"Seu Mac está limpo — nenhum arquivo órfão de apps desinstaladas foi detectado.",
        "ja":"Macはきれいです — アンインストールされたアプリの孤立ファイルは検出されませんでした。",
        "ko":"Mac이 깨끗합니다 — 제거된 앱의 분리된 파일이 감지되지 않았습니다.",
        "zh-Hans":"您的 Mac 很干净 — 未检测到已卸载应用的孤立文件。",
        "zh-Hant":"您的 Mac 很乾淨 — 未偵測到已解除安裝應用程式的孤立檔案。",
    },
    "codenta.us": {
        "it":"codenta.us","es":"codenta.us","fr":"codenta.us","de":"codenta.us","pt":"codenta.us",
        "ja":"codenta.us","ko":"codenta.us","zh-Hans":"codenta.us","zh-Hant":"codenta.us",
    },
    "percent": {
        "it":"percento","es":"por ciento","fr":"pour cent","de":"Prozent","pt":"por cento",
        "ja":"パーセント","ko":"퍼센트","zh-Hans":"百分比","zh-Hant":"百分比",
    },
    "uninstally": {
        "it":"uninstally","es":"uninstally","fr":"uninstally","de":"uninstally","pt":"uninstally",
        "ja":"uninstally","ko":"uninstally","zh-Hans":"uninstally","zh-Hant":"uninstally",
    },
}

def main():
    path = Path(__file__).parent.parent / "Uninstally" / "Localizable.xcstrings"
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    strings = data.get("strings", {})
    fixed = 0

    for key, translations in TRANSLATE.items():
        if key not in strings:
            print(f"SKIP (key not in catalog): {key}")
            continue

        locs = strings[key].setdefault("localizations", {})

        for lang in LANGS:
            if lang in translations:
                translated = translations[lang]
                if lang not in locs:
                    locs[lang] = {}
                locs[lang]["stringUnit"] = {
                    "state": "translated",
                    "value": translated,
                }
                fixed += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Fixed {fixed} translations across {len(TRANSLATE)} keys.")

if __name__ == "__main__":
    main()
