#!/usr/bin/env python3
"""Populate Localizable.xcstrings with placeholder translations for all
supported languages. Existing translations are preserved; only missing or
English-only entries are filled in.

Known strings get proper translations. Unknown strings get a language-tag
prefix (e.g. "[IT] ") so the language switch is immediately visible during
testing.
"""

import json
import sys
from pathlib import Path

TARGET_LANGUAGES = {
    "it": "Italian",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "pt": "Portuguese",
    "ja": "Japanese",
    "ko": "Korean",
    "zh-Hans": "Simplified Chinese",
    "zh-Hant": "Traditional Chinese",
}

# ── Known translations ──────────────────────────────────────────────
# fmt: off
TRANSLATIONS = {
    "it": {
        "Applications": "Applicazioni",
        "Apps": "App",
        "Applications (sidebar)": "Applicazioni",
        "Settings": "Impostazioni",
        "Cancel": "Annulla",
        "Done": "Fatto",
        "Uninstall": "Disinstalla",
        "Delete": "Elimina",
        "Remove": "Rimuovi",
        "Search applications": "Cerca applicazioni",
        "Recently Uninstalled": "Disinstallate di Recente",
        "Collections": "Collezioni",
        "Favorites": "Preferiti",
        "Refresh Applications": "Aggiorna Applicazioni",
        "Storage Insights": "Analisi Archiviazione",
        "Leftover Scanner": "Scansione Residui",
        "Customize Sidebar": "Personalizza Barra",
        "Tools": "Strumenti",
        "Restart Now": "Riavvia Ora",
        "Later": "Più Tardi",
        "Restart Required": "Riavvio Necessario",
        "OK": "OK",
        "Name": "Nome",
        "Size": "Dimensione",
        "Version": "Versione",
        "Category": "Categoria",
        "Developer": "Sviluppatore",
        "Date": "Data",
        "Layout": "Layout",
        "Filter": "Filtro",
        "Sort": "Ordina",
        "Refresh": "Aggiorna",
        "Open": "Apri",
        "Clear History": "Cancella Cronologia",
        "Uninstall History": "Cronologia Disinstallazioni",
        "History Retention": "Conservazione Cronologia",
        "Deletion Method": "Metodo di Eliminazione",
        "Batch Uninstall": "Disinstallazione Multipla",
        "Batch Complete": "Gruppo Completato",
        "Show icon in Dock": "Mostra icona nel Dock",
        "Update Channel": "Canale Aggiornamenti",
        "Reset All Preferences": "Ripristina Preferenze",
        "Restore Defaults": "Ripristina Predefiniti",
        "New Collection": "Nuova Collezione",
        "Rename": "Rinomina",
        "Continue": "Continua",
        "Get Started": "Inizia",
        "Skip": "Salta",
        "Reveal in Finder": "Mostra nel Finder",
        "Reveal Location": "Mostra Posizione",
        "Proceed with Uninstall": "Procedi con Disinstallazione",
        "Select All": "Seleziona Tutto",
        "Deselect All": "Deseleziona Tutto",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "Sito Web",
        "Volume": "Volume",
        "App": "App",
        "Trash": "Cestino",
        "Location": "Posizione",
        "Identifier": "Identificatore",
        "Bundle Identifier": "Identificatore Bundle",
        "Count": "Conteggio",
        "Orphaned Files": "File Orfani",
        "Uninstall…": "Disinstalla…",
    },
    "es": {
        "Applications": "Aplicaciones",
        "Apps": "Aplicaciones",
        "Settings": "Ajustes",
        "Cancel": "Cancelar",
        "Done": "Hecho",
        "Uninstall": "Desinstalar",
        "Delete": "Eliminar",
        "Remove": "Eliminar",
        "Search applications": "Buscar aplicaciones",
        "Recently Uninstalled": "Desinstaladas Recientemente",
        "Collections": "Colecciones",
        "Favorites": "Favoritos",
        "Refresh Applications": "Actualizar Aplicaciones",
        "Storage Insights": "Análisis de Almacenamiento",
        "Leftover Scanner": "Escáner de Residuos",
        "Customize Sidebar": "Personalizar Barra",
        "Tools": "Herramientas",
        "Restart Now": "Reiniciar Ahora",
        "Later": "Más Tarde",
        "Restart Required": "Reinicio Necesario",
        "OK": "Aceptar",
        "Name": "Nombre",
        "Size": "Tamaño",
        "Version": "Versión",
        "Category": "Categoría",
        "Developer": "Desarrollador",
        "Date": "Fecha",
        "Layout": "Diseño",
        "Filter": "Filtro",
        "Sort": "Ordenar",
        "Refresh": "Actualizar",
        "Open": "Abrir",
        "Clear History": "Borrar Historial",
        "Uninstall History": "Historial de Desinstalaciones",
        "History Retention": "Conservación del Historial",
        "Deletion Method": "Método de Eliminación",
        "Batch Uninstall": "Desinstalación por Lotes",
        "Batch Complete": "Lote Completado",
        "Show icon in Dock": "Mostrar icono en el Dock",
        "Update Channel": "Canal de Actualización",
        "Reset All Preferences": "Restablecer Preferencias",
        "Restore Defaults": "Restaurar Predeterminados",
        "New Collection": "Nueva Colección",
        "Rename": "Renombrar",
        "Continue": "Continuar",
        "Get Started": "Comenzar",
        "Skip": "Omitir",
        "Reveal in Finder": "Mostrar en Finder",
        "Reveal Location": "Mostrar Ubicación",
        "Proceed with Uninstall": "Proceder con Desinstalación",
        "Select All": "Seleccionar Todo",
        "Deselect All": "Deseleccionar Todo",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "Sitio Web",
        "Volume": "Volumen",
        "App": "App",
        "Trash": "Papelera",
        "Location": "Ubicación",
        "Identifier": "Identificador",
        "Bundle Identifier": "Identificador de Bundle",
        "Count": "Cantidad",
        "Orphaned Files": "Archivos Huérfanos",
        "Uninstall…": "Desinstalar…",
    },
    "fr": {
        "Applications": "Applications",
        "Apps": "Apps",
        "Settings": "Préférences",
        "Cancel": "Annuler",
        "Done": "Terminé",
        "Uninstall": "Désinstaller",
        "Delete": "Supprimer",
        "Remove": "Supprimer",
        "Search applications": "Rechercher applications",
        "Recently Uninstalled": "Désinstallés Récemment",
        "Collections": "Collections",
        "Favorites": "Favoris",
        "Refresh Applications": "Actualiser Applications",
        "Storage Insights": "Analyse Stockage",
        "Leftover Scanner": "Scanner Résidus",
        "Customize Sidebar": "Personnaliser Barre",
        "Tools": "Outils",
        "Restart Now": "Redémarrer",
        "Later": "Plus Tard",
        "Restart Required": "Redémarrage Requis",
        "OK": "OK",
        "Name": "Nom",
        "Size": "Taille",
        "Version": "Version",
        "Category": "Catégorie",
        "Developer": "Développeur",
        "Date": "Date",
        "Layout": "Disposition",
        "Filter": "Filtre",
        "Sort": "Trier",
        "Refresh": "Actualiser",
        "Open": "Ouvrir",
        "Clear History": "Effacer Historique",
        "Uninstall History": "Historique Désinstallation",
        "History Retention": "Rétention Historique",
        "Deletion Method": "Méthode de Suppression",
        "Batch Uninstall": "Désinstallation Groupée",
        "Batch Complete": "Groupe Terminé",
        "Show icon in Dock": "Afficher l'icône dans le Dock",
        "Update Channel": "Canal de Mise à Jour",
        "Reset All Preferences": "Réinitialiser Préférences",
        "Restore Defaults": "Restaurer Valeurs par Défaut",
        "New Collection": "Nouvelle Collection",
        "Rename": "Renommer",
        "Continue": "Continuer",
        "Get Started": "Commencer",
        "Skip": "Passer",
        "Reveal in Finder": "Afficher dans Finder",
        "Reveal Location": "Afficher Emplacement",
        "Proceed with Uninstall": "Procéder à la Désinstallation",
        "Select All": "Tout Sélectionner",
        "Deselect All": "Tout Désélectionner",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "Site Web",
        "Volume": "Volume",
        "App": "App",
        "Trash": "Corbeille",
        "Location": "Emplacement",
        "Identifier": "Identifiant",
        "Bundle Identifier": "Identifiant de Bundle",
        "Count": "Nombre",
        "Orphaned Files": "Fichiers Orphelins",
        "Uninstall…": "Désinstaller…",
    },
    "de": {
        "Applications": "Anwendungen",
        "Apps": "Apps",
        "Settings": "Einstellungen",
        "Cancel": "Abbrechen",
        "Done": "Fertig",
        "Uninstall": "Deinstallieren",
        "Delete": "Löschen",
        "Remove": "Entfernen",
        "Search applications": "Apps suchen",
        "Recently Uninstalled": "Kürzlich deinstalliert",
        "Collections": "Sammlungen",
        "Favorites": "Favoriten",
        "Refresh Applications": "Apps aktualisieren",
        "Storage Insights": "Speicheranalyse",
        "Leftover Scanner": "Restescanner",
        "Customize Sidebar": "Seitenleiste anpassen",
        "Tools": "Werkzeuge",
        "Restart Now": "Jetzt neu starten",
        "Later": "Später",
        "Restart Required": "Neustart erforderlich",
        "OK": "OK",
        "Name": "Name",
        "Size": "Größe",
        "Version": "Version",
        "Category": "Kategorie",
        "Developer": "Entwickler",
        "Date": "Datum",
        "Layout": "Layout",
        "Filter": "Filter",
        "Sort": "Sortieren",
        "Refresh": "Aktualisieren",
        "Open": "Öffnen",
        "Clear History": "Verlauf löschen",
        "Uninstall History": "Deinstallationsverlauf",
        "History Retention": "Verlaufsspeicherung",
        "Deletion Method": "Löschmethode",
        "Batch Uninstall": "Stapeldeinstallation",
        "Batch Complete": "Stapel abgeschlossen",
        "Show icon in Dock": "Symbol im Dock anzeigen",
        "Update Channel": "Update-Kanal",
        "Reset All Preferences": "Einstellungen zurücksetzen",
        "Restore Defaults": "Standard wiederherstellen",
        "New Collection": "Neue Sammlung",
        "Rename": "Umbenennen",
        "Continue": "Weiter",
        "Get Started": "Loslegen",
        "Skip": "Überspringen",
        "Reveal in Finder": "Im Finder zeigen",
        "Reveal Location": "Ort zeigen",
        "Proceed with Uninstall": "Deinstallation fortsetzen",
        "Select All": "Alle auswählen",
        "Deselect All": "Auswahl aufheben",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "Webseite",
        "Volume": "Volume",
        "App": "App",
        "Trash": "Papierkorb",
        "Location": "Ort",
        "Identifier": "Kennung",
        "Bundle Identifier": "Bundle-Kennung",
        "Count": "Anzahl",
        "Orphaned Files": "Verwaiste Dateien",
        "Uninstall…": "Deinstallieren…",
    },
    "pt": {
        "Applications": "Aplicativos",
        "Apps": "Aplicativos",
        "Settings": "Definições",
        "Cancel": "Cancelar",
        "Done": "Concluído",
        "Uninstall": "Desinstalar",
        "Delete": "Excluir",
        "Remove": "Remover",
        "Search applications": "Pesquisar aplicativos",
        "Recently Uninstalled": "Desinstalados Recentemente",
        "Collections": "Coleções",
        "Favorites": "Favoritos",
        "Refresh Applications": "Atualizar Aplicativos",
        "Storage Insights": "Análise de Armazenamento",
        "Leftover Scanner": "Scanner de Resíduos",
        "Customize Sidebar": "Personalizar Barra",
        "Tools": "Ferramentas",
        "Restart Now": "Reiniciar Agora",
        "Later": "Mais Tarde",
        "Restart Required": "Reinicialização Necessária",
        "OK": "OK",
        "Name": "Nome",
        "Size": "Tamanho",
        "Version": "Versão",
        "Category": "Categoria",
        "Developer": "Desenvolvedor",
        "Date": "Data",
        "Layout": "Layout",
        "Filter": "Filtro",
        "Sort": "Ordenar",
        "Refresh": "Atualizar",
        "Open": "Abrir",
        "Clear History": "Limpar Histórico",
        "Uninstall History": "Histórico de Desinstalação",
        "History Retention": "Retenção do Histórico",
        "Deletion Method": "Método de Exclusão",
        "Batch Uninstall": "Desinstalação em Lote",
        "Batch Complete": "Lote Concluído",
        "Show icon in Dock": "Mostrar ícone no Dock",
        "Update Channel": "Canal de Atualização",
        "Reset All Preferences": "Redefinir Preferências",
        "Restore Defaults": "Restaurar Padrões",
        "New Collection": "Nova Coleção",
        "Rename": "Renomear",
        "Continue": "Continuar",
        "Get Started": "Começar",
        "Skip": "Pular",
        "Reveal in Finder": "Mostrar no Finder",
        "Reveal Location": "Mostrar Localização",
        "Proceed with Uninstall": "Prosseguir com Desinstalação",
        "Select All": "Selecionar Tudo",
        "Deselect All": "Desmarcar Tudo",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "Site",
        "Volume": "Volume",
        "App": "App",
        "Trash": "Lixeira",
        "Location": "Localização",
        "Identifier": "Identificador",
        "Bundle Identifier": "Identificador do Bundle",
        "Count": "Contagem",
        "Orphaned Files": "Arquivos Órfãos",
        "Uninstall…": "Desinstalar…",
    },
    "ja": {
        "Applications": "アプリ",
        "Apps": "アプリ",
        "Settings": "設定",
        "Cancel": "キャンセル",
        "Done": "完了",
        "Uninstall": "アンインストール",
        "Delete": "削除",
        "Remove": "削除",
        "Search applications": "アプリを検索",
        "Recently Uninstalled": "最近アンインストール",
        "Collections": "コレクション",
        "Favorites": "お気に入り",
        "Refresh Applications": "アプリを更新",
        "Storage Insights": "ストレージ分析",
        "Leftover Scanner": "残存スキャナー",
        "Customize Sidebar": "サイドバー設定",
        "Tools": "ツール",
        "Restart Now": "今すぐ再起動",
        "Later": "後で",
        "Restart Required": "再起動が必要",
        "OK": "OK",
        "Name": "名前",
        "Size": "サイズ",
        "Version": "バージョン",
        "Category": "カテゴリ",
        "Developer": "開発者",
        "Date": "日付",
        "Layout": "レイアウト",
        "Filter": "フィルター",
        "Sort": "並べ替え",
        "Refresh": "更新",
        "Open": "開く",
        "Clear History": "履歴を消去",
        "Uninstall History": "アンインストール履歴",
        "History Retention": "履歴の保存期間",
        "Deletion Method": "削除方法",
        "Batch Uninstall": "一括アンインストール",
        "Batch Complete": "一括完了",
        "Show icon in Dock": "Dockにアイコンを表示",
        "Update Channel": "アップデートチャンネル",
        "Reset All Preferences": "設定をリセット",
        "Restore Defaults": "デフォルトに戻す",
        "New Collection": "新規コレクション",
        "Rename": "名前を変更",
        "Continue": "続行",
        "Get Started": "開始",
        "Skip": "スキップ",
        "Reveal in Finder": "Finderで表示",
        "Reveal Location": "場所を表示",
        "Proceed with Uninstall": "アンインストールを実行",
        "Select All": "すべて選択",
        "Deselect All": "選択解除",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "Webサイト",
        "Volume": "ボリューム",
        "App": "アプリ",
        "Trash": "ゴミ箱",
        "Location": "場所",
        "Identifier": "識別子",
        "Bundle Identifier": "バンドル識別子",
        "Count": "カウント",
        "Orphaned Files": "孤立ファイル",
        "Uninstall…": "アンインストール…",
    },
    "ko": {
        "Applications": "앱",
        "Apps": "앱",
        "Settings": "설정",
        "Cancel": "취소",
        "Done": "완료",
        "Uninstall": "제거",
        "Delete": "삭제",
        "Remove": "삭제",
        "Search applications": "앱 검색",
        "Recently Uninstalled": "최근 제거됨",
        "Collections": "컬렉션",
        "Favorites": "즐겨찾기",
        "Refresh Applications": "앱 새로고침",
        "Storage Insights": "저장소 분석",
        "Leftover Scanner": "잔여물 스캐너",
        "Customize Sidebar": "사이드바 설정",
        "Tools": "도구",
        "Restart Now": "지금 다시 시작",
        "Later": "나중에",
        "Restart Required": "다시 시작 필요",
        "OK": "확인",
        "Name": "이름",
        "Size": "크기",
        "Version": "버전",
        "Category": "카테고리",
        "Developer": "개발자",
        "Date": "날짜",
        "Layout": "레이아웃",
        "Filter": "필터",
        "Sort": "정렬",
        "Refresh": "새로고침",
        "Open": "열기",
        "Clear History": "기록 지우기",
        "Uninstall History": "제거 기록",
        "History Retention": "기록 보존",
        "Deletion Method": "삭제 방식",
        "Batch Uninstall": "일괄 제거",
        "Batch Complete": "일괄 완료",
        "Show icon in Dock": "Dock에 아이콘 표시",
        "Update Channel": "업데이트 채널",
        "Reset All Preferences": "모든 설정 초기화",
        "Restore Defaults": "기본값 복원",
        "New Collection": "새 컬렉션",
        "Rename": "이름 변경",
        "Continue": "계속",
        "Get Started": "시작하기",
        "Skip": "건너뛰기",
        "Reveal in Finder": "Finder에서 보기",
        "Reveal Location": "위치 보기",
        "Proceed with Uninstall": "제거 진행",
        "Select All": "전체 선택",
        "Deselect All": "선택 해제",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "웹사이트",
        "Volume": "볼륨",
        "App": "앱",
        "Trash": "휴지통",
        "Location": "위치",
        "Identifier": "식별자",
        "Bundle Identifier": "번들 식별자",
        "Count": "개수",
        "Orphaned Files": "분리된 파일",
        "Uninstall…": "제거…",
    },
    "zh-Hans": {
        "Applications": "应用",
        "Apps": "应用",
        "Settings": "设置",
        "Cancel": "取消",
        "Done": "完成",
        "Uninstall": "卸载",
        "Delete": "删除",
        "Remove": "删除",
        "Search applications": "搜索应用",
        "Recently Uninstalled": "最近卸载",
        "Collections": "收藏",
        "Favorites": "收藏",
        "Refresh Applications": "刷新应用",
        "Storage Insights": "存储分析",
        "Leftover Scanner": "残留扫描",
        "Customize Sidebar": "自定义侧边栏",
        "Tools": "工具",
        "Restart Now": "立即重启",
        "Later": "稍后",
        "Restart Required": "需要重启",
        "OK": "确定",
        "Name": "名称",
        "Size": "大小",
        "Version": "版本",
        "Category": "分类",
        "Developer": "开发者",
        "Date": "日期",
        "Layout": "布局",
        "Filter": "过滤",
        "Sort": "排序",
        "Refresh": "刷新",
        "Open": "打开",
        "Clear History": "清除历史",
        "Uninstall History": "卸载历史",
        "History Retention": "历史保留",
        "Deletion Method": "删除方式",
        "Batch Uninstall": "批量卸载",
        "Batch Complete": "批量完成",
        "Show icon in Dock": "在Dock中显示图标",
        "Update Channel": "更新通道",
        "Reset All Preferences": "重置所有偏好",
        "Restore Defaults": "恢复默认",
        "New Collection": "新建收藏",
        "Rename": "重命名",
        "Continue": "继续",
        "Get Started": "开始",
        "Skip": "跳过",
        "Reveal in Finder": "在Finder中显示",
        "Reveal Location": "显示位置",
        "Proceed with Uninstall": "继续卸载",
        "Select All": "全选",
        "Deselect All": "取消全选",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "网站",
        "Volume": "卷",
        "App": "应用",
        "Trash": "废纸篓",
        "Location": "位置",
        "Identifier": "标识符",
        "Bundle Identifier": "Bundle标识符",
        "Count": "数量",
        "Orphaned Files": "孤立文件",
        "Uninstall…": "卸载…",
    },
    "zh-Hant": {
        "Applications": "應用程式",
        "Apps": "應用程式",
        "Settings": "設定",
        "Cancel": "取消",
        "Done": "完成",
        "Uninstall": "解除安裝",
        "Delete": "刪除",
        "Remove": "刪除",
        "Search applications": "搜尋應用程式",
        "Recently Uninstalled": "最近解除安裝",
        "Collections": "收藏",
        "Favorites": "收藏",
        "Refresh Applications": "重新整理應用程式",
        "Storage Insights": "儲存空間分析",
        "Leftover Scanner": "殘留掃描",
        "Customize Sidebar": "自訂側邊欄",
        "Tools": "工具",
        "Restart Now": "立即重新啟動",
        "Later": "稍後",
        "Restart Required": "需要重新啟動",
        "OK": "確定",
        "Name": "名稱",
        "Size": "大小",
        "Version": "版本",
        "Category": "分類",
        "Developer": "開發者",
        "Date": "日期",
        "Layout": "佈局",
        "Filter": "過濾",
        "Sort": "排序",
        "Refresh": "重新整理",
        "Open": "開啟",
        "Clear History": "清除歷史",
        "Uninstall History": "解除安裝歷史",
        "History Retention": "歷史保留",
        "Deletion Method": "刪除方式",
        "Batch Uninstall": "批次解除安裝",
        "Batch Complete": "批次完成",
        "Show icon in Dock": "在Dock中顯示圖示",
        "Update Channel": "更新通道",
        "Reset All Preferences": "重置所有偏好",
        "Restore Defaults": "恢復預設",
        "New Collection": "新建收藏",
        "Rename": "重新命名",
        "Continue": "繼續",
        "Get Started": "開始",
        "Skip": "跳過",
        "Reveal in Finder": "在Finder中顯示",
        "Reveal Location": "顯示位置",
        "Proceed with Uninstall": "繼續解除安裝",
        "Select All": "全選",
        "Deselect All": "取消全選",
        "Homebrew": "Homebrew",
        "GitHub": "GitHub",
        "Website": "網站",
        "Volume": "卷",
        "App": "應用程式",
        "Trash": "垃圾桶",
        "Location": "位置",
        "Identifier": "識別碼",
        "Bundle Identifier": "Bundle識別碼",
        "Count": "數量",
        "Orphaned Files": "孤立檔案",
        "Uninstall…": "解除安裝…",
    },
}
# fmt: on

# Language indicator prefixes for untranslated strings as a fallback
LANG_TAGS = {
    "it": "[IT] ",
    "es": "[ES] ",
    "fr": "[FR] ",
    "de": "[DE] ",
    "pt": "[PT] ",
    "ja": "[JA] ",
    "ko": "[KO] ",
    "zh-Hans": "[ZH] ",
    "zh-Hant": "[ZH] ",
}


def is_format_string(s: str) -> bool:
    """Return True if the string contains format specifiers like %@ or %lld."""
    return "%" in s


def translate_string(key: str, lang: str, en_value: str) -> str:
    """Return the translated value for *key* and *lang*, or a fallback."""
    known = TRANSLATIONS.get(lang, {})

    if key in known:
        known_val = known[key]
        # For format strings that have translated versions,
        # preserve the positional format markers from en_value if missing
        if is_format_string(en_value) and is_format_string(known_val):
            return known_val
        return known_val

    # Try key variants (strip trailing ... or case-insensitive)
    key_clean = key.rstrip("…").rstrip()
    if key_clean in known:
        known_val = known[key_clean]
        if key.endswith("…"):
            return known_val + "…"
        return known_val

    # Format strings: keep the English source with position markers
    # (e.g. "%1$lld items • %2$@ total") — translating these requires
    # language-specific plural rules, so we keep the source intact.
    if is_format_string(key):
        return en_value

    # For compound patterns like "Uninstall %@", try to translate parts
    if key.endswith("?"):
        inner = key[:-1].rstrip()
        if inner in known:
            return known[inner] + "？" if lang in ("ja", "ko", "zh-Hans", "zh-Hant") else known[inner] + " ?"

    # Fallback: language tag prefix to make the switch visible
    tag = LANG_TAGS.get(lang, "")
    if en_value:
        return tag + en_value
    return tag + key


def main():
    xcstrings_path = Path(__file__).parent.parent / "Uninstally" / "Localizable.xcstrings"
    if not xcstrings_path.exists():
        print(f"ERROR: {xcstrings_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(xcstrings_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    strings = data.get("strings", {})
    updated = 0
    added = 0

    for key, entry in strings.items():
        if not isinstance(entry, dict):
            continue
        if not key:
            continue

        locs = entry.setdefault("localizations", {})

        # Get the English value (source text)
        en_unit = locs.get("en", {}).get("stringUnit", {})
        en_value = en_unit.get("value", key)

        for lang_code in TARGET_LANGUAGES:
            if lang_code in locs:
                lang_entry = locs[lang_code]
                if not isinstance(lang_entry, dict):
                    locs[lang_code] = {}
                    lang_entry = locs[lang_code]
                unit = lang_entry.get("stringUnit", {})
                current_val = unit.get("value", "")
                current_state = unit.get("state", "")

                # Skip if already properly translated (not English and not needs_review with English)
                if current_state == "translated" and current_val != en_value:
                    continue

                # Update with our translation
                translated = translate_string(key, lang_code, en_value)
                if "stringUnit" not in lang_entry:
                    lang_entry["stringUnit"] = {}
                lang_entry["stringUnit"]["state"] = "translated"
                lang_entry["stringUnit"]["value"] = translated
                updated += 1
            else:
                # Language entry doesn't exist yet
                translated = translate_string(key, lang_code, en_value)
                locs[lang_code] = {
                    "stringUnit": {
                        "state": "translated",
                        "value": translated,
                    }
                }
                added += 1

    data["strings"] = strings

    with open(xcstrings_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Done. Updated {updated} existing entries, added {added} new entries.")


if __name__ == "__main__":
    main()
