#!/usr/bin/env python3
"""Master translation script: provides high-quality translations for every
String Catalog entry across all 10 supported languages. Existing [XX] prefix
placeholders are replaced with proper target-language text.

Usage: python3 translate_all.py
"""

import json, re, sys
from pathlib import Path

LANGUAGES = ["it", "es", "fr", "de", "pt", "ja", "ko", "zh-Hans", "zh-Hant"]

# ── Master translation dictionaries ─────────────────────────────────
T = {}  # lang_code -> { en_key : translated_value }

T["it"] = {
    # App & general
    "Uninstally": "Uninstally",
    "uninstally": "uninstally",
    "A native macOS uninstaller by Codenta.": "Un disinstallatore nativo macOS di Codenta.",
    "Website": "Sito Web",
    "GitHub": "GitHub",
    "codenta.us": "codenta.us",
    "Applications": "Applicazioni",
    "Apps": "App",
    "App": "App",
    "OK": "OK",
    "Cancel": "Annulla",
    "Done": "Fatto",
    "Continue": "Continua",
    "Skip": "Salta",
    "Get Started": "Inizia",
    "Open": "Apri",
    "Close": "Chiudi",
    "Save": "Salva",
    "Reset": "Ripristina",
    "Rename": "Rinomina",
    "Rename\u2026": "Rinomina\u2026",
    "Delete": "Elimina",
    "Remove": "Rimuovi",
    "Uninstall": "Disinstalla",
    "Uninstall\u2026": "Disinstalla\u2026",
    "Refresh": "Aggiorna",
    "Refresh Applications": "Aggiorna Applicazioni",
    "Search applications": "Cerca applicazioni",
    "Search apps and leftovers": "Cerca app e residui",
    "Search packages": "Cerca pacchetti",
    "Search history": "Cerca nella cronologia",
    "Search files": "Cerca file",
    "Search leftovers": "Cerca residui",
    "Filter": "Filtro",
    "Sort": "Ordina",
    "Sort By": "Ordina per",
    "Layout": "Layout",
    "Name": "Nome",
    "Size": "Dimensione",
    "Developer": "Sviluppatore",
    "Version": "Versione",
    "Category": "Categoria",
    "Date": "Data",
    "Count": "Numero",
    "Select": "Seleziona",
    "Select All": "Seleziona Tutto",
    "Deselect All": "Deseleziona Tutto",
    "Confirm": "Conferma",
    "Settings": "Impostazioni",
    "Open Settings": "Apri Impostazioni",
    "Settings sections": "Sezioni Impostazioni",
    "Tools": "Strumenti",
    "Refresh the application list": "Aggiorna la lista applicazioni",
    "Later": "Pi\u00f9 Tardi",
    "Restart Now": "Riavvia Ora",
    "Restart Required": "Riavvio Necessario",
    "Never": "Mai",

    # Sidebar & navigation
    "Collections": "Collezioni",
    "New Collection": "Nuova Collezione",
    "New Collection\u2026": "Nuova Collezione\u2026",
    "Favorites": "Preferiti",
    "All Applications": "Tutte le Applicazioni",
    "Largest": "Pi\u00f9 Grandi",
    "Recently Installed": "Installate di Recente",
    "Recently Opened": "Aperte di Recente",
    "Never Opened": "Mai Aperte",
    "With Leftover Files": "Con File Residui",
    "Broken Installs": "Installazioni Danneggiate",
    "Duplicated Across Drives": "Duplicate su Pi\u00f9 Dischi",
    "Largest Apps": "App Pi\u00f9 Grandi",
    "Customize Sidebar": "Personalizza Barra",
    "Customize Sidebar\u2026": "Personalizza Barra\u2026",
    "Customize sidebar and Collections": "Personalizza barra e Collezioni",
    "Customize Collections\u2026": "Personalizza Collezioni\u2026",
    "Hide from Sidebar": "Nascondi dalla Barra",
    "Show or hide in the sidebar": "Mostra o nascondi nella barra",
    "Pin to Top": "Fissa in Alto",
    "Unpin from Top": "Rimuovi dai Preferiti",
    "Delete Collection": "Elimina Collezione",
    "Rename Collection": "Rinomina Collezione",
    "Enter a new name for this collection.": "Inserisci un nuovo nome per la collezione.",
    "Collection name": "Nome collezione",
    "Collection Not Found": "Collezione non Trovata",
    "Select a Category": "Seleziona una Categoria",
    "No Collections": "Nessuna Collezione",
    "Empty Collection": "Collezione Vuota",
    "No Applications": "Nessuna Applicazione",
    "Nothing matches this filter.": "Nessun risultato per questo filtro.",
    "No matching applications": "Nessuna applicazione corrispondente",
    "No matching files": "Nessun file corrispondente",
    "Drag to reorder": "Trascina per riordinare",
    "Choose an icon": "Scegli un\u2019icona",
    "Untitled Collection": "Collezione Senza Nome",
    "Sections": "Sezioni",
    "Organize the Applications sidebar and your Collections.": "Organizza la barra Applicazioni e le tue Collezioni.",
    "Hidden sections stay available \u2014 they're only removed from the sidebar.": "Le sezioni nascoste restano disponibili \u2014 sono solo rimosse dalla barra.",
    "Restore Defaults": "Ripristina Predefiniti",
    "Create a Collection to group and categorize apps. Add apps by dragging them onto a Collection or right-clicking an app.": "Crea una Collezione per raggruppare e categorizzare le app. Aggiungi app trascinandole su una Collezione o con clic destro.",
    "Collections only organize apps \u2014 they never change what's installed.": "Le Collezioni organizzano solo le app \u2014 non cambiano mai ci\u00f2 che \u00e8 installato.",
    "Recently Uninstalled": "Disinstallate di Recente",

    # Leftover Scanner
    "Leftover Scanner": "Scansione Residui",
    "Orphaned Files": "File Orfani",
    "Rescan": "Ripeti Scansione",
    "Scanning for orphaned files\u2026": "Scansione file orfani in corso\u2026",
    "No Leftovers Found": "Nessun Residuo Trovato",
    "Your Mac is tidy \u2014 no orphaned files from uninstalled apps were detected.": "Il tuo Mac \u00e8 pulito \u2014 nessun file orfano da app disinstallate \u00e8 stato rilevato.",
    "Remove Selected": "Rimuovi Selezionati",
    "No orphaned files found": "Nessun file orfano trovato",
    "Remove %lld leftover items?": "Rimuovere %lld elementi residui?",
    "Remove %lld Items": "Rimuovi %lld Elementi",
    "Open the Leftover Scanner to review and remove orphaned files": "Apri la Scansione Residui per esaminare e rimuovere i file orfani",
    "Scanning for leftovers\u2026": "Scansione residui in corso\u2026",
    "Remove Leftovers": "Rimuovi Residui",

    # Uninstall
    "Uninstall %@?": "Disinstallare %@?",
    "Move to Trash": "Sposta nel Cestino",
    "Permanently Delete": "Elimina Definitivamente",
    "Delete Permanently": "Elimina Definitivamente",
    "Safer option. Files can be recovered from the Trash.": "Opzione pi\u00f9 sicura. I file possono essere recuperati dal Cestino.",
    "Removes files immediately and cannot be undone.": "Rimuove i file immediatamente e non pu\u00f2 essere annullato.",
    "Deletion Method": "Metodo di Eliminazione",
    "Uninstall Summary": "Riepilogo Disinstallazione",
    "Uninstall Simulation": "Simulazione Disinstallazione",
    "Simulation Report": "Report Simulazione",
    "Detailed Breakdown": "Dettaglio Completo",
    "Storage Analysis": "Analisi Archiviazione",
    "Total Recoverable Storage": "Spazio Totale Recuperabile",
    "Shared Resources": "Risorse Condivise",
    "Security Summary": "Riepilogo Sicurezza",
    "Batch Uninstall": "Disinstallazione Multipla",
    "Batch Complete": "Gruppo Completato",
    "This will permanently delete the selected apps. This action cannot be undone.": "Le app selezionate saranno eliminate definitivamente. Quest\u2019azione non pu\u00f2 essere annullata.",
    "The selected apps and their files will be moved to the Trash.": "Le app selezionate e i loro file saranno spostati nel Cestino.",
    "Uninstall All": "Disinstalla Tutto",
    "Review Individually": "Esamina Singolarmente",
    "Proceed with Uninstall": "Procedi con la Disinstallazione",
    "Simulating uninstall of %@": "Simulazione disinstallazione di %@",
    "Removing %@": "Rimozione di %@",
    "Successfully Removed": "Rimosso con Successo",
    "Removed with Issues": "Rimosso con Problemi",
    "This window will close automatically.": "Questa finestra si chiuder\u00e0 automaticamente.",
    "This simulation has not deleted any files.": "Questa simulazione non ha eliminato alcun file.",
    "Uninstally simulated each app. Nothing has been deleted.": "Uninstally ha simulato ogni app. Nulla \u00e8 stato eliminato.",
    "These items may be used by other software. Review them before removing \u2014 deselect any you want to keep.": "Questi elementi potrebbero essere usati da altri software. Esaminali prima di rimuovere \u2014 deseleziona quelli da conservare.",
    "This install appears to be broken or incomplete": "Questa installazione sembra danneggiata o incompleta",
    "Reveal in Finder": "Mostra nel Finder",
    "Reveal Location": "Mostra Posizione",
    "Reveal Original Location": "Mostra Posizione Originale",
    "Show in Finder": "Mostra nel Finder",
    "Copy Path": "Copia Percorso",
    "Requires administrator privileges": "Richiede privilegi di amministratore",
    "Broken": "Danneggiato",
    "Add to Collection": "Aggiungi alla Collezione",
    "Remove from Collection": "Rimuovi dalla Collezione",
    "View Details": "Visualizza Dettagli",
    "Restore from Trash": "Ripristina dal Cestino",
    "Remove From History": "Rimuovi dalla Cronologia",
    "No longer in the Trash": "Non pi\u00f9 nel Cestino",
    "Move the app back to its original location": "Riporta l\u2019app nella sua posizione originale",

    # Progress
    "Preparing\u2026": "Preparazione\u2026",
    "Scanning application\u2026": "Scansione applicazione\u2026",
    "Searching containers, caches and preferences\u2026": "Ricerca container, cache e preferenze\u2026",
    "Searching login items, launch agents and services\u2026": "Ricerca elementi login, agenti di avvio e servizi\u2026",
    "Validating every path\u2026": "Convalida di ogni percorso\u2026",
    "Calculating storage\u2026": "Calcolo archiviazione\u2026",
    "Scanning your applications\u2026": "Scansione delle tue applicazioni\u2026",
    "Refreshing\u2026": "Aggiornamento\u2026",
    "Resolving dependencies\u2026": "Risoluzione dipendenze\u2026",

    # Files & storage
    "%@ will be permanently deleted. This cannot be undone.": "%@ sar\u00e0 eliminato definitivamente. Non pu\u00f2 essere annullato.",
    "%@ will be moved to the Trash.": "%@ sar\u00e0 spostato nel Cestino.",
    "%lld applications \u2022 about %@ reclaimable": "%lld applicazioni \u2022 circa %@ recuperabili",
    "%lld selected": "%lld selezionati",
    "About %@ reclaimable": "Circa %@ recuperabili",
    "Removed %lld applications": "%lld applicazioni rimosse",
    "Reclaimed": "Recuperato",
    "Files Removed": "File Rimossi",
    "Time Taken": "Tempo Impiegato",
    "%lld items could not be removed": "%lld elementi non rimossi",
    "%lld Applications Selected": "%lld Applicazioni Selezionate",
    "%lld files": "%lld file",
    "%lld files across %lld apps": "%lld file su %lld app",
    "%lld of %lld": "%lld di %lld",
    "%lld of %lld items": "%lld di %lld elementi",
    "percent": "percento",
    "Items": "Elementi",
    "Removed": "Rimossi",
    "Remaining": "Rimanenti",
    "reclaimable": "recuperabile",
    "Total Files": "File Totali",
    "Recoverable": "Recuperabile",
    "Categories": "Categorie",
    "Background Components": "Componenti in Background",
    "Services": "Servizi",
    "Estimated Time": "Tempo Stimato",
    "Application": "Applicazione",
    "Application Support": "Supporto Applicazione",
    "Caches": "Cache",
    "Preferences": "Preferenze",
    "Saved State": "Stato Salvato",
    "Logs": "Log",
    "Containers": "Container",
    "Group Containers": "Container di Gruppo",
    "Cookies": "Cookie",
    "WebKit Data": "Dati WebKit",
    "HTTP Storage": "Archiviazione HTTP",
    "Temporary Files": "File Temporanei",
    "Launch Agents": "Agenti di Avvio",
    "Launch Daemons": "Demoni di Avvio",
    "Login Items": "Elementi di Login",
    "Extensions": "Estensioni",
    "Crash Reports": "Report Crash",
    "Spotlight Metadata": "Metadati Spotlight",
    "QuickLook Plugins": "Plugin QuickLook",
    "Privileged Helpers": "Helper Privilegiati",
    "Widgets": "Widget",
    "Other Support Files": "Altri File di Supporto",
    "Support Files": "File di Supporto",
    "Other": "Altro",
    "Related Files": "File Correlati",
    "Login Items Removed": "Elementi Login Rimossi",
    "Launch Agents Removed": "Agenti Avvio Rimossi",
    "Background Services Removed": "Servizi in Background Rimossi",
    "Finder Extensions Removed": "Estensioni Finder Rimosse",
    "Cache Folders Removed": "Cartelle Cache Rimosse",
    "Preference Files Removed": "File Preferenze Rimossi",
    "Saved State Removed": "Stato Salvato Rimosso",

    # History
    "Uninstall History": "Cronologia Disinstallazioni",
    "Clear History": "Cancella Cronologia",
    "Clear\u2026": "Cancella\u2026",
    "Clear all uninstall history?": "Cancellare tutta la cronologia?",
    "Clear all history": "Cancella tutta la cronologia",
    "Remove every entry from the uninstall history.": "Rimuovi ogni voce dalla cronologia.",
    "This permanently removes every entry. It does not affect files already in the Trash.": "Rimuove definitivamente ogni voce. Non influisce sui file gi\u00e0 nel Cestino.",
    "This permanently removes every entry from the history. It does not affect files already in the Trash.": "Rimuove definitivamente ogni voce dalla cronologia. Non influisce sui file gi\u00e0 nel Cestino.",
    "Apps you remove with Uninstally will appear here, so you can review or restore them.": "Le app rimosse con Uninstally appariranno qui, per esaminarle o ripristinarle.",
    "History Retention": "Conservazione Cronologia",
    "Automatically remove entries older than this.": "Rimuovi automaticamente voci pi\u00f9 vecchie di questo periodo.",
    "30 Days": "30 Giorni",
    "90 Days": "90 Giorni",
    "1 Year": "1 Anno",
    "Forever": "Per Sempre",
    "Filter history": "Filtra cronologia",
    "No Uninstall History": "Nessuna Cronologia",
    "Couldn't Restore": "Impossibile Ripristinare",
    "Apps Uninstalled": "App Disinstallate",
    "Uninstalled": "Disinstallato",
    "Storage Recovered": "Spazio Recuperato",
    "Last Uninstall": "Ultima Disinstallazione",
    "Average Recovered": "Media Recuperata",
    "Original Location": "Posizione Originale",
    "Location": "Posizione",
    "Identifier": "Identificatore",
    "Bundle Identifier": "Identificatore Bundle",
    "Installed": "Installato",
    "Last Used": "Ultimo Utilizzo",
    "Volume": "Volume",
    "Today": "Oggi",
    "Last 7 Days": "Ultimi 7 Giorni",
    "Last 30 Days": "Ultimi 30 Giorni",
    "All Time": "Sempre",
    "Trash": "Cestino",
    "Deleted": "Eliminato",
    "Permanent Delete": "Eliminazione Definitiva",

    # Settings
    "Updates": "Aggiornamenti",
    "Appearance": "Aspetto",
    "Language": "Lingua",
    "Uninstall Settings": "Impostazioni Disinstallazione",
    "Scanning": "Scansione",
    "Security": "Sicurezza",
    "Advanced": "Avanzate",
    "About": "Informazioni",
    "Keep Uninstally up to date.": "Mantieni Uninstally aggiornato.",
    "How Uninstally looks and where it lives.": "Come appare Uninstally e dove risiede.",
    "Choose the language used throughout the app.": "Scegli la lingua usata nell\u2019app.",
    "What happens when you remove an app.": "Cosa succede quando rimuovi un\u2019app.",
    "How thoroughly Uninstally searches for related files.": "Quanto approfonditamente Uninstally cerca i file correlati.",
    "Confirmations and safe-removal safeguards.": "Conferme e protezioni per la rimozione sicura.",
    "Power-user options and resets.": "Opzioni avanzate e ripristini.",
    "Version and links.": "Versione e collegamenti.",
    "Show icon in Dock": "Mostra icona nel Dock",
    "When off, Uninstally runs as a lightweight accessory with no Dock or menu-bar presence.": "Quando disattivato, Uninstally si avvia come accessorio senza Dock n\u00e9 barra dei menu.",
    "Source language \u2014 translation ready": "Lingua sorgente \u2014 traduzione pronta",
    "The application needs to restart to apply the selected language.": "L\u2019applicazione deve essere riavviata per applicare la lingua selezionata.",
    "Quit after a Finder uninstall": "Esci dopo disinstallazione da Finder",
    "Automatically close Uninstally once a right-click uninstall finishes.": "Chiudi automaticamente Uninstally al termine della disinstallazione.",
    "Keep Uninstall History": "Conserva Cronologia Disinstallazioni",
    "Record apps you remove so you can review or restore them from Recently Uninstalled.": "Registra le app rimosse per revisione o ripristino da Disinstallate di Recente.",
    "Include system-level files": "Includi file di sistema",
    "Also search /Library locations. Removing these requires an administrator password.": "Cerca anche in /Library. La rimozione richiede password amministratore.",
    "Scan for leftovers automatically": "Scansiona automaticamente i residui",
    "Look for orphaned files from removed apps in the background.": "Cerca file orfani da app rimosse in background.",
    "Monitor Trash for Deleted Applications": "Monitora Cestino per App Eliminate",
    "When you drag an app to the Trash in Finder, offer to remove its leftover files.": "Quando trascini un\u2019app nel Cestino, offri di rimuovere i file residui.",
    "Require confirmation before deleting": "Richiedi conferma prima di eliminare",
    "Always show a summary and warning before anything is removed.": "Mostra sempre riepilogo e avviso prima della rimozione.",
    "Verified update source": "Fonte aggiornamenti verificata",
    "Updates are only downloaded from the official Uninstally repository on GitHub and verified before installation.": "Gli aggiornamenti sono scaricati solo dal repository ufficiale Uninstally su GitHub e verificati prima dell\u2019installazione.",
    "Reset All Preferences": "Ripristina Tutte le Preferenze",
    "Restore Uninstally's settings, sidebar layout and collections to their defaults. Takes effect on next launch.": "Ripristina impostazioni, layout barra e collezioni ai valori predefiniti. Effettivo al prossimo avvio.",
    "Preferences reset. Relaunch to see all changes.": "Preferenze ripristinate. Riavvia per vedere le modifiche.",
    "Current Version": "Versione Corrente",
    "Latest Version": "Ultima Versione",
    "Last Checked": "Ultimo Controllo",
    "Status": "Stato",
    "Automatically Check for Updates": "Controlla Aggiornamenti Automaticamente",
    "Automatically Download Updates": "Scarica Aggiornamenti Automaticamente",
    "Receive Beta Updates": "Ricevi Aggiornamenti Beta",
    "Include pre-release builds from the selected channel.": "Includi build pre-release dal canale selezionato.",
    "Check Now": "Controlla Ora",
    "Clear Ignored Version": "Cancella Versione Ignorata",
    "Reset Update Preferences": "Ripristina Preferenze Aggiornamenti",
    "Update Channel": "Canale Aggiornamenti",
    "Enable beta updates to choose a pre-release channel.": "Abilita aggiornamenti beta per scegliere un canale pre-release.",
    "Not checked yet": "Non ancora controllato",
    "Checking\u2026": "Verifica in corso\u2026",
    "You're up to date": "Sei aggiornato",
    "Stable": "Stabile",
    "Beta": "Beta",
    "Nightly": "Notturno",
    "Update Available": "Aggiornamento Disponibile",
    "Update available: %@": "Aggiornamento disponibile: %@",

    # Storage Insights
    "Storage Insights": "Analisi Archiviazione",
    "Installed Applications": "Applicazioni Installate",
    "Total Installed Size": "Dimensione Totale Installata",
    "Largest Installed App": "App Installata Pi\u00f9 Grande",
    "Total Space Recovered": "Spazio Totale Recuperato",
    "Apps Removed": "App Rimosse",
    "Average Space Recovered": "Spazio Medio Recuperato",
    "Unused Applications": "Applicazioni Inutilizzate",
    "Largest Applications": "Applicazioni Pi\u00f9 Grandi",
    "Largest Leftover Files": "File Residui Pi\u00f9 Grandi",
    "Never Opened": "Mai Aperte",
    "Not Opened in 90 Days": "Non Aperte da 90 Giorni",
    "This Week": "Questa Settimana",
    "This Month": "Questo Mese",
    "Lifetime": "Totale",
    "Installed %@": "Installato %@",
    "Opened %@": "Aperto %@",
    "Storage by Category": "Archiviazione per Categoria",
    "Recovered Storage Over Time": "Spazio Recuperato nel Tempo",
    "Not enough history yet": "Cronologia insufficiente",
    "Installed Apps by Developer": "App Installate per Sviluppatore",
    "Application Count by Category": "Conteggio App per Categoria",
    "No data yet": "Nessun dato disponibile",

    # Homebrew
    "Homebrew Not Found": "Homebrew non Trovato",
    "Install Homebrew from brew.sh to manage command-line packages and casks here.": "Installa Homebrew da brew.sh per gestire pacchetti e casks da riga di comando.",
    "Reading Homebrew packages\u2026": "Lettura pacchetti Homebrew\u2026",
    "Required by (will break):": "Richiesto da (si romper\u00e0):",
    "Depends on:": "Dipende da:",
    "No dependency relationships detected.": "Nessuna dipendenza rilevata.",
    "Also remove configuration & leftover files (--zap)": "Rimuovi anche configurazione e file residui (--zap)",
    "Cask": "Cask",
    "Formula": "Formula",

    # Notifications
    "Scan Leftovers": "Scansiona Residui",
    "Dismiss": "Ignora",
    "Uninstall Complete": "Disinstallazione Completata",
    "Uninstall Finished with Issues": "Disinstallazione Completata con Problemi",
    "Application Moved to Trash": "Applicazione Spostata nel Cestino",
    "Uninstally found leftover files for %@. Would you like to remove them?": "Uninstally ha trovato file residui per %@. Vuoi rimuoverli?",

    # Security
    "Applications and related files will be moved to the Trash. You can restore them until the Trash is emptied.": "Le applicazioni e i file correlati saranno spostati nel Cestino. Puoi ripristinarli fino allo svuotamento del Cestino.",
    "Applications and related files will be permanently deleted. This action cannot be undone.": "Le applicazioni e i file correlati saranno eliminati definitivamente. Quest\u2019azione non pu\u00f2 essere annullata.",
    "Could not confirm this belongs to %@": "Impossibile confermare che appartenga a %@",
    "Item still present after deletion": "Elemento ancora presente dopo l\u2019eliminazione",
    "Failed to remove %@: %@": "Rimozione di %@ fallita: %@",
    "Path no longer exists": "Il percorso non esiste pi\u00f9",
    "Protected system location": "Posizione di sistema protetta",
    "Too close to a root directory": "Troppo vicino a una directory root",
    "Refuses to delete an approved root directory": "Rifiutata eliminazione di directory root approvata",
    "Outside every approved location": "Fuori da ogni posizione approvata",
    "Broken alias": "Alias danneggiato",
    "The application bundle": "Il bundle dell\u2019applicazione",
    "Named for %@": "Nominato per %@",
    "Folder named after %@": "Cartella nominata come %@",
    "Preferences for %@": "Preferenze per %@",

    # Error
    "Homebrew is not installed.": "Homebrew non \u00e8 installato.",
    "Uninstall failed.": "Disinstallazione fallita.",
    "Network error: %@": "Errore di rete: %@",
    "Couldn't read the release information from GitHub.": "Impossibile leggere le informazioni di rilascio da GitHub.",
    "GitHub rate limit reached. Please try again later.": "Limite di richieste GitHub raggiunto. Riprova pi\u00f9 tardi.",
    "The latest release has no downloadable DMG.": "L\u2019ultima release non ha un DMG scaricabile.",
    "The update came from an untrusted source and was blocked.": "L\u2019aggiornamento proviene da fonte non attendibile ed \u00e8 stato bloccato.",
    "Couldn't mount the downloaded disk image.": "Impossibile montare l\u2019immagine disco scaricata.",
    "The disk image didn't contain Uninstally.": "L\u2019immagine disco non conteneva Uninstally.",
    "Update verification failed: %@": "Verifica aggiornamento fallita: %@",
    "Couldn't install the update: %@": "Impossibile installare l\u2019aggiornamento: %@",
    "The update was cancelled.": "L\u2019aggiornamento \u00e8 stato annullato.",

    # Misc
    "Sort By": "Ordina per",
    "Install Date": "Data Installazione",
    "Recently Used": "Usate di Recente",
    "Unused": "Inutilizzate",
    "Change the sort order": "Cambia ordinamento",
    "Swap between grid and list": "Alterna tra griglia e lista",
    "Off": "Off",
    "On": "On",
    "Select multiple applications to uninstall together": "Seleziona pi\u00f9 applicazioni da disinstallare insieme",
    "Welcome to Uninstally": "Benvenuto in Uninstally",
    "The cleanest way to completely remove apps and every file they leave behind.": "Il modo pi\u00f9 pulito per rimuovere completamente le app e tutti i file che lasciano.",
    "Smart Detection": "Rilevamento Intelligente",
    "Uninstally matches files by bundle identifier \u2014 not just by name \u2014 across every Library location, so nothing gets missed and nothing unrelated gets touched.": "Uninstally abbina i file per identificatore bundle \u2014 non solo per nome \u2014 in ogni posizione Libreria, cos\u00ec nulla viene tralasciato e nulla di estraneo viene toccato.",
    "Safe by Design": "Sicuro per Progetto",
    "You review everything before it's removed. Files go to the Trash where possible, and admin actions ask for permission only when needed.": "Esamini tutto prima della rimozione. I file vanno nel Cestino dove possibile, e le azioni admin chiedono permesso solo quando necessario.",
    "Uninstally matches files by bundle identifier \u2014 not just by name \u2014 across every Library location, so nothing gets missed and nothing unrelated gets touched.": "Uninstally abbina i file per identificatore bundle \u2014 non solo per nome \u2014 in ogni posizione Libreria.",
}

# ── Spanish ──────────────────────────────────────────────────────────
T["es"] = {
    "Uninstally": "Uninstally",
    "uninstally": "uninstally",
    "A native macOS uninstaller by Codenta.": "Un desinstalador nativo macOS de Codenta.",
    "Website": "Sitio Web",
    "GitHub": "GitHub",
    "codenta.us": "codenta.us",
    "Applications": "Aplicaciones",
    "Apps": "Aplicaciones",
    "App": "App",
    "OK": "Aceptar",
    "Cancel": "Cancelar",
    "Done": "Hecho",
    "Continue": "Continuar",
    "Skip": "Omitir",
    "Get Started": "Comenzar",
    "Open": "Abrir",
    "Close": "Cerrar",
    "Save": "Guardar",
    "Reset": "Restablecer",
    "Rename": "Renombrar",
    "Rename\u2026": "Renombrar\u2026",
    "Delete": "Eliminar",
    "Remove": "Eliminar",
    "Uninstall": "Desinstalar",
    "Uninstall\u2026": "Desinstalar\u2026",
    "Refresh": "Actualizar",
    "Refresh Applications": "Actualizar Aplicaciones",
    "Search applications": "Buscar aplicaciones",
    "Search apps and leftovers": "Buscar apps y residuos",
    "Search packages": "Buscar paquetes",
    "Search history": "Buscar en historial",
    "Search files": "Buscar archivos",
    "Search leftovers": "Buscar residuos",
    "Filter": "Filtro",
    "Sort": "Ordenar",
    "Sort By": "Ordenar por",
    "Layout": "Dise\u00f1o",
    "Name": "Nombre",
    "Size": "Tama\u00f1o",
    "Developer": "Desarrollador",
    "Version": "Versi\u00f3n",
    "Category": "Categor\u00eda",
    "Date": "Fecha",
    "Count": "Cantidad",
    "Select": "Seleccionar",
    "Select All": "Seleccionar Todo",
    "Deselect All": "Deseleccionar Todo",
    "Confirm": "Confirmar",
    "Settings": "Ajustes",
    "Open Settings": "Abrir Ajustes",
    "Settings sections": "Secciones de Ajustes",
    "Tools": "Herramientas",
    "Refresh the application list": "Actualizar la lista de aplicaciones",
    "Later": "M\u00e1s Tarde",
    "Restart Now": "Reiniciar Ahora",
    "Restart Required": "Reinicio Necesario",
    "Never": "Nunca",

    "Collections": "Colecciones",
    "New Collection": "Nueva Colecci\u00f3n",
    "New Collection\u2026": "Nueva Colecci\u00f3n\u2026",
    "Favorites": "Favoritos",
    "All Applications": "Todas las Aplicaciones",
    "Largest": "M\u00e1s Grandes",
    "Recently Installed": "Instaladas Recientemente",
    "Recently Opened": "Abiertas Recientemente",
    "Never Opened": "Nunca Abiertas",
    "With Leftover Files": "Con Archivos Residuales",
    "Broken Installs": "Instalaciones Da\u00f1adas",
    "Duplicated Across Drives": "Duplicadas en Varios Discos",
    "Largest Apps": "Apps M\u00e1s Grandes",
    "Customize Sidebar": "Personalizar Barra",
    "Customize Sidebar\u2026": "Personalizar Barra\u2026",
    "Customize sidebar and Collections": "Personalizar barra y Colecciones",
    "Customize Collections\u2026": "Personalizar Colecciones\u2026",
    "Hide from Sidebar": "Ocultar de la Barra",
    "Show or hide in the sidebar": "Mostrar u ocultar en la barra lateral",
    "Pin to Top": "Fijar Arriba",
    "Unpin from Top": "Desfijar",
    "Delete Collection": "Eliminar Colecci\u00f3n",
    "Rename Collection": "Renombrar Colecci\u00f3n",
    "Enter a new name for this collection.": "Introduce un nuevo nombre para esta colecci\u00f3n.",
    "Collection name": "Nombre de la colecci\u00f3n",
    "Collection Not Found": "Colecci\u00f3n no Encontrada",
    "Select a Category": "Seleccionar una Categor\u00eda",
    "No Collections": "Sin Colecciones",
    "Empty Collection": "Colecci\u00f3n Vac\u00eda",
    "No Applications": "Sin Aplicaciones",
    "Nothing matches this filter.": "Nada coincide con este filtro.",
    "No matching applications": "Sin aplicaciones coincidentes",
    "No matching files": "Sin archivos coincidentes",
    "Drag to reorder": "Arrastrar para reordenar",
    "Choose an icon": "Elegir un icono",
    "Untitled Collection": "Colecci\u00f3n sin T\u00edtulo",
    "Sections": "Secciones",
    "Organize the Applications sidebar and your Collections.": "Organiza la barra de Aplicaciones y tus Colecciones.",
    "Hidden sections stay available \u2014 they're only removed from the sidebar.": "Las secciones ocultas siguen disponibles \u2014 solo se eliminan de la barra.",
    "Restore Defaults": "Restaurar Predeterminados",
    "Create a Collection to group and categorize apps. Add apps by dragging them onto a Collection or right-clicking an app.": "Crea una Colecci\u00f3n para agrupar apps. A\u00f1ade apps arrastr\u00e1ndolas a una Colecci\u00f3n o con clic derecho.",
    "Collections only organize apps \u2014 they never change what's installed.": "Las Colecciones solo organizan apps \u2014 nunca cambian lo instalado.",
    "Recently Uninstalled": "Desinstaladas Recientemente",

    "Leftover Scanner": "Esc\u00e1ner de Residuos",
    "Orphaned Files": "Archivos Hu\u00e9rfanos",
    "Rescan": "Volver a Escanear",
    "Scanning for orphaned files\u2026": "Escaneando archivos hu\u00e9rfanos\u2026",
    "No Leftovers Found": "Sin Residuos Encontrados",
    "Your Mac is tidy \u2014 no orphaned files from uninstalled apps were detected.": "Tu Mac est\u00e1 limpio \u2014 no se detectaron archivos hu\u00e9rfanos.",
    "Remove Selected": "Eliminar Seleccionados",
    "No orphaned files found": "Sin archivos hu\u00e9rfanos encontrados",
    "Remove %lld leftover items?": "\u00bfEliminar %lld elementos residuales?",
    "Remove %lld Items": "Eliminar %lld Elementos",
    "Open the Leftover Scanner to review and remove orphaned files": "Abre el Esc\u00e1ner de Residuos para revisar archivos hu\u00e9rfanos",
    "Scanning for leftovers\u2026": "Buscando residuos\u2026",
    "Remove Leftovers": "Eliminar Residuos",

    "Uninstall %@?": "\u00bfDesinstalar %@?",
    "Move to Trash": "Mover a la Papelera",
    "Permanently Delete": "Eliminar Permanentemente",
    "Delete Permanently": "Eliminar Permanentemente",
    "Safer option. Files can be recovered from the Trash.": "Opci\u00f3n m\u00e1s segura. Los archivos pueden recuperarse de la Papelera.",
    "Removes files immediately and cannot be undone.": "Elimina archivos inmediatamente y no se puede deshacer.",
    "Deletion Method": "M\u00e9todo de Eliminaci\u00f3n",
    "Uninstall Summary": "Resumen de Desinstalaci\u00f3n",
    "Uninstall Simulation": "Simulaci\u00f3n de Desinstalaci\u00f3n",
    "Simulation Report": "Informe de Simulaci\u00f3n",
    "Detailed Breakdown": "Desglose Detallado",
    "Storage Analysis": "An\u00e1lisis de Almacenamiento",
    "Total Recoverable Storage": "Almacenamiento Total Recuperable",
    "Shared Resources": "Recursos Compartidos",
    "Security Summary": "Resumen de Seguridad",
    "Batch Uninstall": "Desinstalaci\u00f3n por Lotes",
    "Batch Complete": "Lote Completado",
    "This will permanently delete the selected apps. This action cannot be undone.": "Esto eliminar\u00e1 permanentemente las apps seleccionadas. No se puede deshacer.",
    "The selected apps and their files will be moved to the Trash.": "Las apps seleccionadas y sus archivos se mover\u00e1n a la Papelera.",
    "Uninstall All": "Desinstalar Todo",
    "Review Individually": "Revisar Individualmente",
    "Proceed with Uninstall": "Proceder con Desinstalaci\u00f3n",
    "Simulating uninstall of %@": "Simulando desinstalaci\u00f3n de %@",
    "Removing %@": "Eliminando %@",
    "Successfully Removed": "Eliminado con \u00c9xito",
    "Removed with Issues": "Eliminado con Problemas",
    "This window will close automatically.": "Esta ventana se cerrar\u00e1 autom\u00e1ticamente.",
    "This simulation has not deleted any files.": "Esta simulaci\u00f3n no ha eliminado ning\u00fan archivo.",
    "Uninstally simulated each app. Nothing has been deleted.": "Uninstally simul\u00f3 cada app. No se ha eliminado nada.",
    "These items may be used by other software. Review them before removing \u2014 deselect any you want to keep.": "Estos elementos pueden ser usados por otro software. Rev\u00edsalos antes de eliminar.",
    "This install appears to be broken or incomplete": "Esta instalaci\u00f3n parece da\u00f1ada o incompleta",
    "Reveal in Finder": "Mostrar en Finder",
    "Reveal Location": "Mostrar Ubicaci\u00f3n",
    "Reveal Original Location": "Mostrar Ubicaci\u00f3n Original",
    "Show in Finder": "Mostrar en Finder",
    "Copy Path": "Copiar Ruta",
    "Requires administrator privileges": "Requiere privilegios de administrador",
    "Broken": "Da\u00f1ado",
    "Add to Collection": "A\u00f1adir a Colecci\u00f3n",
    "Remove from Collection": "Quitar de Colecci\u00f3n",
    "View Details": "Ver Detalles",
    "Restore from Trash": "Restaurar de Papelera",
    "Remove From History": "Eliminar del Historial",
    "No longer in the Trash": "Ya no est\u00e1 en la Papelera",
    "Move the app back to its original location": "Mover la app a su ubicaci\u00f3n original",

    "Preparing\u2026": "Preparando\u2026",
    "Scanning application\u2026": "Escaneando aplicaci\u00f3n\u2026",
    "Searching containers, caches and preferences\u2026": "Buscando contenedores, cach\u00e9s y preferencias\u2026",
    "Searching login items, launch agents and services\u2026": "Buscando \u00edtems de inicio, agentes y servicios\u2026",
    "Validating every path\u2026": "Validando cada ruta\u2026",
    "Calculating storage\u2026": "Calculando almacenamiento\u2026",
    "Scanning your applications\u2026": "Escaneando tus aplicaciones\u2026",
    "Refreshing\u2026": "Actualizando\u2026",
    "Resolving dependencies\u2026": "Resolviendo dependencias\u2026",

    "%@ will be permanently deleted. This cannot be undone.": "%@ se eliminar\u00e1 permanentemente. No se puede deshacer.",
    "%@ will be moved to the Trash.": "%@ se mover\u00e1 a la Papelera.",
    "%lld applications \u2022 about %@ reclaimable": "%lld aplicaciones \u2022 aproximadamente %@ recuperables",
    "%lld selected": "%lld seleccionados",
    "About %@ reclaimable": "Aprox. %@ recuperables",
    "Removed %lld applications": "%lld aplicaciones eliminadas",
    "Reclaimed": "Recuperado",
    "Files Removed": "Archivos Eliminados",
    "Time Taken": "Tiempo Transcurrido",
    "%lld items could not be removed": "%lld elementos no se pudieron eliminar",
    "%lld Applications Selected": "%lld Aplicaciones Seleccionadas",
    "%lld files": "%lld archivos",
    "%lld files across %lld apps": "%lld archivos en %lld apps",
    "%lld of %lld": "%lld de %lld",
    "%lld of %lld items": "%lld de %lld elementos",
    "percent": "por ciento",
    "Items": "Elementos",
    "Removed": "Eliminados",
    "Remaining": "Restantes",
    "reclaimable": "recuperable",
    "Total Files": "Archivos Totales",
    "Recoverable": "Recuperable",
    "Categories": "Categor\u00edas",
    "Background Components": "Componentes en Segundo Plano",
    "Services": "Servicios",
    "Estimated Time": "Tiempo Estimado",
    "Application": "Aplicaci\u00f3n",
    "Application Support": "Soporte de Aplicaci\u00f3n",
    "Caches": "Cach\u00e9s",
    "Preferences": "Preferencias",
    "Saved State": "Estado Guardado",
    "Logs": "Registros",
    "Containers": "Contenedores",
    "Group Containers": "Contenedores de Grupo",
    "Cookies": "Cookies",
    "WebKit Data": "Datos WebKit",
    "HTTP Storage": "Almacenamiento HTTP",
    "Temporary Files": "Archivos Temporales",
    "Launch Agents": "Agentes de Inicio",
    "Launch Daemons": "Demonios de Inicio",
    "Login Items": "Elementos de Inicio",
    "Extensions": "Extensiones",
    "Crash Reports": "Informes de Fallos",
    "Spotlight Metadata": "Metadatos Spotlight",
    "QuickLook Plugins": "Plugins QuickLook",
    "Privileged Helpers": "Asistentes Privilegiados",
    "Widgets": "Widgets",
    "Other Support Files": "Otros Archivos de Soporte",
    "Support Files": "Archivos de Soporte",
    "Other": "Otro",
    "Related Files": "Archivos Relacionados",
    "Login Items Removed": "Elementos de Inicio Eliminados",
    "Launch Agents Removed": "Agentes de Inicio Eliminados",
    "Background Services Removed": "Servicios en Segundo Plano Eliminados",
    "Finder Extensions Removed": "Extensiones de Finder Eliminadas",
    "Cache Folders Removed": "Carpetas de Cach\u00e9 Eliminadas",
    "Preference Files Removed": "Archivos de Preferencias Eliminados",
    "Saved State Removed": "Estado Guardado Eliminado",

    "Uninstall History": "Historial de Desinstalaci\u00f3n",
    "Clear History": "Borrar Historial",
    "Clear\u2026": "Borrar\u2026",
    "Clear all uninstall history?": "\u00bfBorrar todo el historial?",
    "Clear all history": "Borrar todo el historial",
    "Remove every entry from the uninstall history.": "Eliminar cada entrada del historial.",
    "This permanently removes every entry. It does not affect files already in the Trash.": "Elimina permanentemente cada entrada. No afecta archivos en la Papelera.",
    "This permanently removes every entry from the history. It does not affect files already in the Trash.": "Elimina permanentemente cada entrada del historial.",
    "Apps you remove with Uninstally will appear here, so you can review or restore them.": "Las apps que elimines con Uninstally aparecer\u00e1n aqu\u00ed para revisarlas o restaurarlas.",
    "History Retention": "Conservaci\u00f3n del Historial",
    "Automatically remove entries older than this.": "Eliminar autom\u00e1ticamente entradas m\u00e1s antiguas.",
    "30 Days": "30 D\u00edas",
    "90 Days": "90 D\u00edas",
    "1 Year": "1 A\u00f1o",
    "Forever": "Para Siempre",
    "Filter history": "Filtrar historial",
    "No Uninstall History": "Sin Historial de Desinstalaci\u00f3n",
    "Couldn't Restore": "No se Pudo Restaurar",
    "Apps Uninstalled": "Apps Desinstaladas",
    "Uninstalled": "Desinstalado",
    "Storage Recovered": "Almacenamiento Recuperado",
    "Last Uninstall": "\u00daltima Desinstalaci\u00f3n",
    "Average Recovered": "Promedio Recuperado",
    "Original Location": "Ubicaci\u00f3n Original",
    "Location": "Ubicaci\u00f3n",
    "Identifier": "Identificador",
    "Bundle Identifier": "Identificador de Bundle",
    "Installed": "Instalado",
    "Last Used": "\u00daltimo Uso",
    "Volume": "Volumen",
    "Today": "Hoy",
    "Last 7 Days": "\u00daltimos 7 D\u00edas",
    "Last 30 Days": "\u00daltimos 30 D\u00edas",
    "All Time": "Todo el Tiempo",
    "Trash": "Papelera",
    "Deleted": "Eliminado",
    "Permanent Delete": "Eliminaci\u00f3n Permanente",

    "Updates": "Actualizaciones",
    "Appearance": "Apariencia",
    "Language": "Idioma",
    "Uninstall Settings": "Ajustes de Desinstalaci\u00f3n",
    "Scanning": "Escaneo",
    "Security": "Seguridad",
    "Advanced": "Avanzado",
    "About": "Acerca de",
    "Keep Uninstally up to date.": "Mantener Uninstally actualizado.",
    "How Uninstally looks and where it lives.": "C\u00f3mo se ve Uninstally y d\u00f3nde reside.",
    "Choose the language used throughout the app.": "Elegir el idioma usado en la aplicaci\u00f3n.",
    "What happens when you remove an app.": "Qu\u00e9 sucede al eliminar una app.",
    "How thoroughly Uninstally searches for related files.": "Con qu\u00e9 exhaustividad busca Uninstally archivos relacionados.",
    "Confirmations and safe-removal safeguards.": "Confirmaciones y protecciones de eliminaci\u00f3n segura.",
    "Power-user options and resets.": "Opciones avanzadas y restablecimientos.",
    "Version and links.": "Versi\u00f3n y enlaces.",
    "Show icon in Dock": "Mostrar icono en el Dock",
    "When off, Uninstally runs as a lightweight accessory with no Dock or menu-bar presence.": "Desactivado, Uninstally se ejecuta como accesorio ligero sin presencia en Dock.",
    "Source language \u2014 translation ready": "Idioma fuente \u2014 traducci\u00f3n lista",
    "The application needs to restart to apply the selected language.": "La aplicaci\u00f3n debe reiniciarse para aplicar el idioma seleccionado.",
    "Quit after a Finder uninstall": "Salir tras desinstalaci\u00f3n del Finder",
    "Automatically close Uninstally once a right-click uninstall finishes.": "Cerrar Uninstally autom\u00e1ticamente al finalizar la desinstalaci\u00f3n.",
    "Keep Uninstall History": "Conservar Historial de Desinstalaciones",
    "Record apps you remove so you can review or restore them from Recently Uninstalled.": "Registrar apps eliminadas para revisarlas en Desinstaladas Recientemente.",
    "Include system-level files": "Incluir archivos del sistema",
    "Also search /Library locations. Removing these requires an administrator password.": "Buscar tambi\u00e9n en /Library. Requiere contrase\u00f1a de administrador.",
    "Scan for leftovers automatically": "Escanear residuos autom\u00e1ticamente",
    "Look for orphaned files from removed apps in the background.": "Buscar archivos hu\u00e9rfanos en segundo plano.",
    "Monitor Trash for Deleted Applications": "Monitorizar Papelera para Apps Eliminadas",
    "When you drag an app to the Trash in Finder, offer to remove its leftover files.": "Al arrastrar una app a la Papelera, ofrecer eliminar sus residuos.",
    "Require confirmation before deleting": "Requerir confirmaci\u00f3n antes de eliminar",
    "Always show a summary and warning before anything is removed.": "Mostrar siempre resumen y advertencia antes de eliminar.",
    "Verified update source": "Fuente de actualizaci\u00f3n verificada",
    "Updates are only downloaded from the official Uninstally repository on GitHub and verified before installation.": "Las actualizaciones se descargan solo del repositorio oficial.",
    "Reset All Preferences": "Restablecer Todas las Preferencias",
    "Restore Uninstally's settings, sidebar layout and collections to their defaults. Takes effect on next launch.": "Restaurar ajustes, barra lateral y colecciones a predeterminados.",
    "Preferences reset. Relaunch to see all changes.": "Preferencias restablecidas. Reinicia para ver los cambios.",
    "Current Version": "Versi\u00f3n Actual",
    "Latest Version": "\u00daltima Versi\u00f3n",
    "Last Checked": "\u00daltima Comprobaci\u00f3n",
    "Status": "Estado",
    "Automatically Check for Updates": "Buscar Actualizaciones Autom\u00e1ticamente",
    "Automatically Download Updates": "Descargar Actualizaciones Autom\u00e1ticamente",
    "Receive Beta Updates": "Recibir Actualizaciones Beta",
    "Include pre-release builds from the selected channel.": "Incluir builds prelanzamiento del canal seleccionado.",
    "Check Now": "Comprobar Ahora",
    "Clear Ignored Version": "Limpiar Versi\u00f3n Ignorada",
    "Reset Update Preferences": "Restablecer Preferencias de Actualizaci\u00f3n",
    "Update Channel": "Canal de Actualizaci\u00f3n",
    "Enable beta updates to choose a pre-release channel.": "Activar actualizaciones beta para elegir canal prelanzamiento.",
    "Not checked yet": "No comprobado a\u00fan",
    "Checking\u2026": "Comprobando\u2026",
    "You're up to date": "Est\u00e1s al d\u00eda",
    "Stable": "Estable",
    "Beta": "Beta",
    "Nightly": "Nocturno",
    "Update Available": "Actualizaci\u00f3n Disponible",
    "Update available: %@": "Actualizaci\u00f3n disponible: %@",

    "Storage Insights": "An\u00e1lisis de Almacenamiento",
    "Installed Applications": "Aplicaciones Instaladas",
    "Total Installed Size": "Tama\u00f1o Total Instalado",
    "Largest Installed App": "App Instalada M\u00e1s Grande",
    "Total Space Recovered": "Espacio Total Recuperado",
    "Apps Removed": "Apps Eliminadas",
    "Average Space Recovered": "Espacio Medio Recuperado",
    "Unused Applications": "Aplicaciones Sin Usar",
    "Largest Applications": "Aplicaciones M\u00e1s Grandes",
    "Largest Leftover Files": "Archivos Residuales M\u00e1s Grandes",
    "Not Opened in 90 Days": "Sin Abrir en 90 D\u00edas",
    "This Week": "Esta Semana",
    "This Month": "Este Mes",
    "Lifetime": "Total",
    "Installed %@": "Instalado %@",
    "Opened %@": "Abierto %@",
    "Storage by Category": "Almacenamiento por Categor\u00eda",
    "Recovered Storage Over Time": "Almacenamiento Recuperado en el Tiempo",
    "Not enough history yet": "Historial insuficiente",
    "Installed Apps by Developer": "Apps Instaladas por Desarrollador",
    "Application Count by Category": "Conteo de Apps por Categor\u00eda",
    "No data yet": "Sin datos a\u00fan",

    "Homebrew Not Found": "Homebrew no Encontrado",
    "Install Homebrew from brew.sh to manage command-line packages and casks here.": "Instala Homebrew desde brew.sh para gestionar paquetes y casks.",
    "Reading Homebrew packages\u2026": "Leyendo paquetes de Homebrew\u2026",
    "Required by (will break):": "Requerido por (se romper\u00e1):",
    "Depends on:": "Depende de:",
    "No dependency relationships detected.": "Sin dependencias detectadas.",
    "Also remove configuration & leftover files (--zap)": "Eliminar tambi\u00e9n configuraci\u00f3n y archivos residuales (--zap)",
    "Cask": "Cask",
    "Formula": "F\u00f3rmula",

    "Scan Leftovers": "Escanear Residuos",
    "Dismiss": "Descartar",
    "Uninstall Complete": "Desinstalaci\u00f3n Completa",
    "Uninstall Finished with Issues": "Desinstalaci\u00f3n con Problemas",
    "Application Moved to Trash": "App Movida a la Papelera",
    "Uninstally found leftover files for %@. Would you like to remove them?": "Uninstally encontr\u00f3 archivos residuales para %@. \u00bfQuieres eliminarlos?",

    "Applications and related files will be moved to the Trash. You can restore them until the Trash is emptied.": "Las aplicaciones y archivos se mover\u00e1n a la Papelera. Puedes restaurarlos hasta vaciarla.",
    "Applications and related files will be permanently deleted. This action cannot be undone.": "Las aplicaciones y archivos se eliminar\u00e1n permanentemente.",
    "Could not confirm this belongs to %@": "No se pudo confirmar que pertenezca a %@",
    "Item still present after deletion": "Elemento a\u00fan presente tras eliminaci\u00f3n",
    "Failed to remove %@: %@": "Error al eliminar %@: %@",
    "Path no longer exists": "La ruta ya no existe",
    "Protected system location": "Ubicaci\u00f3n de sistema protegida",
    "Too close to a root directory": "Demasiado cerca de un directorio ra\u00edz",
    "Refuses to delete an approved root directory": "Se rechaza eliminar directorio ra\u00edz aprobado",
    "Outside every approved location": "Fuera de toda ubicaci\u00f3n aprobada",
    "Broken alias": "Alias roto",
    "The application bundle": "El bundle de la aplicaci\u00f3n",
    "Named for %@": "Nombrado por %@",
    "Folder named after %@": "Carpeta nombrada como %@",
    "Preferences for %@": "Preferencias para %@",

    "Homebrew is not installed.": "Homebrew no est\u00e1 instalado.",
    "Uninstall failed.": "Desinstalaci\u00f3n fallida.",
    "Network error: %@": "Error de red: %@",
    "Couldn't read the release information from GitHub.": "No se pudo leer la informaci\u00f3n de GitHub.",
    "GitHub rate limit reached. Please try again later.": "L\u00edmite de GitHub alcanzado. Int\u00e9ntalo m\u00e1s tarde.",
    "The latest release has no downloadable DMG.": "La \u00faltima versi\u00f3n no tiene DMG descargable.",
    "The update came from an untrusted source and was blocked.": "La actualizaci\u00f3n de fuente no confiable fue bloqueada.",
    "Couldn't mount the downloaded disk image.": "No se pudo montar la imagen de disco.",
    "The disk image didn't contain Uninstally.": "La imagen de disco no conten\u00eda Uninstally.",
    "Update verification failed: %@": "Verificaci\u00f3n de actualizaci\u00f3n fallida: %@",
    "Couldn't install the update: %@": "No se pudo instalar la actualizaci\u00f3n: %@",
    "The update was cancelled.": "La actualizaci\u00f3n fue cancelada.",

    "Sort By": "Ordenar por",
    "Install Date": "Fecha de Instalaci\u00f3n",
    "Recently Used": "Usadas Recientemente",
    "Unused": "Sin Usar",
    "Change the sort order": "Cambiar orden",
    "Swap between grid and list": "Alternar entre cuadr\u00edcula y lista",
    "Off": "Apagado",
    "On": "Encendido",
    "Select multiple applications to uninstall together": "Seleccionar m\u00faltiples aplicaciones para desinstalar juntas",
    "Welcome to Uninstally": "Bienvenido a Uninstally",
    "The cleanest way to completely remove apps and every file they leave behind.": "La forma m\u00e1s limpia de eliminar completamente las apps y sus archivos.",
    "Smart Detection": "Detecci\u00f3n Inteligente",
    "Safe by Design": "Seguro por Dise\u00f1o",
    "You review everything before it's removed. Files go to the Trash where possible, and admin actions ask for permission only when needed.": "Revisas todo antes de eliminar. Los archivos van a la Papelera cuando es posible.",
}

# ── French ───────────────────────────────────────────────────────────
T["fr"] = {
    "Uninstally": "Uninstally",
    "uninstally": "uninstally",
    "A native macOS uninstaller by Codenta.": "Un d\u00e9sinstallateur natif macOS par Codenta.",
    "Website": "Site Web",
    "GitHub": "GitHub",
    "codenta.us": "codenta.us",
    "Applications": "Applications",
    "Apps": "Apps",
    "App": "App",
    "OK": "OK",
    "Cancel": "Annuler",
    "Done": "Termin\u00e9",
    "Continue": "Continuer",
    "Skip": "Passer",
    "Get Started": "Commencer",
    "Open": "Ouvrir",
    "Close": "Fermer",
    "Save": "Enregistrer",
    "Reset": "R\u00e9initialiser",
    "Rename": "Renommer",
    "Rename\u2026": "Renommer\u2026",
    "Delete": "Supprimer",
    "Remove": "Supprimer",
    "Uninstall": "D\u00e9sinstaller",
    "Uninstall\u2026": "D\u00e9sinstaller\u2026",
    "Refresh": "Actualiser",
    "Refresh Applications": "Actualiser Applications",
    "Search applications": "Rechercher applications",
    "Search apps and leftovers": "Rechercher apps et r\u00e9sidus",
    "Search packages": "Rechercher paquets",
    "Search history": "Rechercher historique",
    "Search files": "Rechercher fichiers",
    "Search leftovers": "Rechercher r\u00e9sidus",
    "Filter": "Filtre",
    "Sort": "Trier",
    "Sort By": "Trier par",
    "Layout": "Disposition",
    "Name": "Nom",
    "Size": "Taille",
    "Developer": "D\u00e9veloppeur",
    "Version": "Version",
    "Category": "Cat\u00e9gorie",
    "Date": "Date",
    "Count": "Nombre",
    "Select": "S\u00e9lectionner",
    "Select All": "Tout S\u00e9lectionner",
    "Deselect All": "Tout D\u00e9s\u00e9lectionner",
    "Confirm": "Confirmer",
    "Settings": "Pr\u00e9f\u00e9rences",
    "Open Settings": "Ouvrir Pr\u00e9f\u00e9rences",
    "Settings sections": "Sections Pr\u00e9f\u00e9rences",
    "Tools": "Outils",
    "Refresh the application list": "Actualiser la liste des applications",
    "Later": "Plus Tard",
    "Restart Now": "Red\u00e9marrer",
    "Restart Required": "Red\u00e9marrage Requis",
    "Never": "Jamais",

    "Collections": "Collections",
    "New Collection": "Nouvelle Collection",
    "New Collection\u2026": "Nouvelle Collection\u2026",
    "Favorites": "Favoris",
    "All Applications": "Toutes les Applications",
    "Largest": "Plus Grandes",
    "Recently Installed": "Install\u00e9es R\u00e9cemment",
    "Recently Opened": "Ouvertes R\u00e9cemment",
    "Never Opened": "Jamais Ouvertes",
    "With Leftover Files": "Avec Fichiers R\u00e9siduels",
    "Broken Installs": "Installations Endommag\u00e9es",
    "Duplicated Across Drives": "Dupliqu\u00e9es sur Plusieurs Disques",
    "Largest Apps": "Apps les Plus Grosses",
    "Customize Sidebar": "Personnaliser la Barre",
    "Customize Sidebar\u2026": "Personnaliser la Barre\u2026",
    "Customize sidebar and Collections": "Personnaliser barre et Collections",
    "Customize Collections\u2026": "Personnaliser Collections\u2026",
    "Hide from Sidebar": "Masquer de la Barre",
    "Show or hide in the sidebar": "Afficher ou masquer dans la barre",
    "Pin to Top": "\u00c9pingler en Haut",
    "Unpin from Top": "D\u00e9s\u00e9pingler",
    "Delete Collection": "Supprimer la Collection",
    "Rename Collection": "Renommer la Collection",
    "Enter a new name for this collection.": "Saisissez un nouveau nom pour cette collection.",
    "Collection name": "Nom de la collection",
    "Collection Not Found": "Collection Introuvable",
    "Select a Category": "S\u00e9lectionner une Cat\u00e9gorie",
    "No Collections": "Aucune Collection",
    "Empty Collection": "Collection Vide",
    "No Applications": "Aucune Application",
    "Nothing matches this filter.": "Aucun r\u00e9sultat pour ce filtre.",
    "No matching applications": "Aucune application correspondante",
    "No matching files": "Aucun fichier correspondant",
    "Drag to reorder": "Glisser pour r\u00e9organiser",
    "Choose an icon": "Choisir une ic\u00f4ne",
    "Untitled Collection": "Collection sans Nom",
    "Sections": "Sections",
    "Organize the Applications sidebar and your Collections.": "Organisez la barre Applications et vos Collections.",
    "Hidden sections stay available \u2014 they're only removed from the sidebar.": "Les sections masqu\u00e9es restent disponibles.",
    "Restore Defaults": "Restaurer les Valeurs par D\u00e9faut",
    "Create a Collection to group and categorize apps. Add apps by dragging them onto a Collection or right-clicking an app.": "Cr\u00e9ez une Collection pour regrouper les apps.",
    "Collections only organize apps \u2014 they never change what's installed.": "Les Collections organisent seulement les apps.",
    "Recently Uninstalled": "D\u00e9sinstall\u00e9s R\u00e9cemment",

    "Leftover Scanner": "Scanner de R\u00e9sidus",
    "Orphaned Files": "Fichiers Orphelins",
    "Rescan": "Relancer Scan",
    "Scanning for orphaned files\u2026": "Analyse des fichiers orphelins\u2026",
    "No Leftovers Found": "Aucun R\u00e9sidu Trouv\u00e9",
    "Your Mac is tidy \u2014 no orphaned files from uninstalled apps were detected.": "Votre Mac est propre.",
    "Remove Selected": "Supprimer S\u00e9lection",
    "No orphaned files found": "Aucun fichier orphelin trouv\u00e9",
    "Remove %lld leftover items?": "Supprimer %lld \u00e9l\u00e9ments r\u00e9siduels\u00a0?",
    "Remove %lld Items": "Supprimer %lld \u00c9l\u00e9ments",
    "Open the Leftover Scanner to review and remove orphaned files": "Ouvrir le Scanner de R\u00e9sidus",
    "Scanning for leftovers\u2026": "Recherche de r\u00e9sidus\u2026",
    "Remove Leftovers": "Supprimer R\u00e9sidus",

    "Uninstall %@?": "D\u00e9sinstaller %@\u00a0?",
    "Move to Trash": "Mettre \u00e0 la Corbeille",
    "Permanently Delete": "Supprimer D\u00e9finitivement",
    "Delete Permanently": "Supprimer D\u00e9finitivement",
    "Safer option. Files can be recovered from the Trash.": "Option s\u00fbre. Les fichiers peuvent \u00eatre r\u00e9cup\u00e9r\u00e9s.",
    "Removes files immediately and cannot be undone.": "Supprime d\u00e9finitivement et ne peut \u00eatre annul\u00e9.",
    "Deletion Method": "M\u00e9thode de Suppression",
    "Uninstall Summary": "R\u00e9sum\u00e9 de D\u00e9sinstallation",
    "Uninstall Simulation": "Simulation de D\u00e9sinstallation",
    "Simulation Report": "Rapport de Simulation",
    "Detailed Breakdown": "D\u00e9tail Complet",
    "Storage Analysis": "Analyse Stockage",
    "Total Recoverable Storage": "Stockage R\u00e9cup\u00e9rable Total",
    "Shared Resources": "Ressources Partag\u00e9es",
    "Security Summary": "R\u00e9sum\u00e9 de S\u00e9curit\u00e9",
    "Batch Uninstall": "D\u00e9sinstallation Group\u00e9e",
    "Batch Complete": "Groupe Termin\u00e9",
    "This will permanently delete the selected apps. This action cannot be undone.": "Les apps s\u00e9lectionn\u00e9es seront supprim\u00e9es d\u00e9finitivement.",
    "The selected apps and their files will be moved to the Trash.": "Les apps et leurs fichiers seront mis \u00e0 la Corbeille.",
    "Uninstall All": "Tout D\u00e9sinstaller",
    "Review Individually": "Examiner Individuellement",
    "Proceed with Uninstall": "Proc\u00e9der \u00e0 la D\u00e9sinstallation",
    "Simulating uninstall of %@": "Simulation de d\u00e9sinstallation de %@",
    "Removing %@": "Suppression de %@",
    "Successfully Removed": "Supprim\u00e9 avec Succ\u00e8s",
    "Removed with Issues": "Supprim\u00e9 avec Probl\u00e8mes",
    "This window will close automatically.": "Cette fen\u00eatre se fermera automatiquement.",
    "This simulation has not deleted any files.": "Cette simulation n\u2019a supprim\u00e9 aucun fichier.",
    "Uninstally simulated each app. Nothing has been deleted.": "Uninstally a simul\u00e9 chaque app. Rien n\u2019a \u00e9t\u00e9 supprim\u00e9.",
    "These items may be used by other software. Review them before removing \u2014 deselect any you want to keep.": "Ces \u00e9l\u00e9ments peuvent \u00eatre utilis\u00e9s par d\u2019autres logiciels.",
    "This install appears to be broken or incomplete": "Cette installation semble endommag\u00e9e",
    "Reveal in Finder": "Afficher dans le Finder",
    "Reveal Location": "Afficher l\u2019Emplacement",
    "Reveal Original Location": "Afficher Emplacement d\u2019Origine",
    "Show in Finder": "Afficher dans le Finder",
    "Copy Path": "Copier le Chemin",
    "Requires administrator privileges": "N\u00e9cessite des privil\u00e8ges admin",
    "Broken": "Endommag\u00e9",
    "Add to Collection": "Ajouter \u00e0 la Collection",
    "Remove from Collection": "Retirer de la Collection",
    "View Details": "Voir D\u00e9tails",
    "Restore from Trash": "Restaurer de la Corbeille",
    "Remove From History": "Supprimer de l\u2019Historique",
    "No longer in the Trash": "Plus dans la Corbeille",
    "Move the app back to its original location": "Remettre l\u2019app \u00e0 son emplacement d\u2019origine",

    "Preparing\u2026": "Pr\u00e9paration\u2026",
    "Scanning application\u2026": "Analyse de l\u2019application\u2026",
    "Searching containers, caches and preferences\u2026": "Recherche conteneurs, caches et pr\u00e9f\u00e9rences\u2026",
    "Searching login items, launch agents and services\u2026": "Recherche \u00e9l\u00e9ments d\u2019ouverture, agents et services\u2026",
    "Validating every path\u2026": "Validation de chaque chemin\u2026",
    "Calculating storage\u2026": "Calcul du stockage\u2026",
    "Scanning your applications\u2026": "Analyse de vos applications\u2026",
    "Refreshing\u2026": "Actualisation\u2026",
    "Resolving dependencies\u2026": "R\u00e9solution d\u00e9pendances\u2026",

    "%@ will be permanently deleted. This cannot be undone.": "%@ sera supprim\u00e9 d\u00e9finitivement.",
    "%@ will be moved to the Trash.": "%@ sera mis \u00e0 la Corbeille.",
    "%lld applications \u2022 about %@ reclaimable": "%lld applications \u2022 environ %@ r\u00e9cup\u00e9rables",
    "%lld selected": "%lld s\u00e9lectionn\u00e9s",
    "About %@ reclaimable": "Environ %@ r\u00e9cup\u00e9rables",
    "Removed %lld applications": "%lld applications supprim\u00e9es",
    "Reclaimed": "R\u00e9cup\u00e9r\u00e9",
    "Files Removed": "Fichiers Supprim\u00e9s",
    "Time Taken": "Temps \u00c9coul\u00e9",
    "%lld items could not be removed": "%lld \u00e9l\u00e9ments non supprim\u00e9s",
    "%lld Applications Selected": "%lld Applications S\u00e9lectionn\u00e9es",
    "%lld files": "%lld fichiers",
    "%lld files across %lld apps": "%lld fichiers sur %lld apps",
    "%lld of %lld": "%lld sur %lld",
    "%lld of %lld items": "%lld sur %lld \u00e9l\u00e9ments",
    "percent": "pour cent",
    "Items": "\u00c9l\u00e9ments",
    "Removed": "Supprim\u00e9s",
    "Remaining": "Restants",
    "reclaimable": "r\u00e9cup\u00e9rable",
    "Total Files": "Total Fichiers",
    "Recoverable": "R\u00e9cup\u00e9rable",
    "Categories": "Cat\u00e9gories",
    "Background Components": "Composants d\u2019Arri\u00e8re-plan",
    "Services": "Services",
    "Estimated Time": "Temps Estim\u00e9",
    "Application": "Application",
    "Application Support": "Support d\u2019Application",
    "Caches": "Caches",
    "Preferences": "Pr\u00e9f\u00e9rences",
    "Saved State": "\u00c9tat Enregistr\u00e9",
    "Logs": "Journaux",
    "Containers": "Conteneurs",
    "Group Containers": "Conteneurs de Groupe",
    "Cookies": "Cookies",
    "WebKit Data": "Donn\u00e9es WebKit",
    "HTTP Storage": "Stockage HTTP",
    "Temporary Files": "Fichiers Temporaires",
    "Launch Agents": "Agents de Lancement",
    "Launch Daemons": "D\u00e9mons de Lancement",
    "Login Items": "Ouverture de Session",
    "Extensions": "Extensions",
    "Crash Reports": "Rapports de Crash",
    "Spotlight Metadata": "M\u00e9tadonn\u00e9es Spotlight",
    "QuickLook Plugins": "Plugins QuickLook",
    "Privileged Helpers": "Assistants Privil\u00e9gi\u00e9s",
    "Widgets": "Widgets",
    "Other Support Files": "Autres Fichiers de Support",
    "Support Files": "Fichiers de Support",
    "Other": "Autre",
    "Related Files": "Fichiers Associ\u00e9s",
    "Login Items Removed": "Ouverture Session Retir\u00e9e",
    "Launch Agents Removed": "Agents Lancement Retir\u00e9s",
    "Background Services Removed": "Services Arri\u00e8re-plan Retir\u00e9s",
    "Finder Extensions Removed": "Extensions Finder Retir\u00e9es",
    "Cache Folders Removed": "Dossiers Cache Retir\u00e9s",
    "Preference Files Removed": "Fichiers Pr\u00e9f\u00e9rences Retir\u00e9s",
    "Saved State Removed": "\u00c9tat Enregistr\u00e9 Retir\u00e9",

    "Uninstall History": "Historique D\u00e9sinstallation",
    "Clear History": "Effacer Historique",
    "Clear\u2026": "Effacer\u2026",
    "Clear all uninstall history?": "Effacer tout l\u2019historique\u00a0?",
    "Clear all history": "Effacer tout l\u2019historique",
    "Remove every entry from the uninstall history.": "Supprimer chaque entr\u00e9e de l\u2019historique.",
    "This permanently removes every entry. It does not affect files already in the Trash.": "Supprime d\u00e9finitivement chaque entr\u00e9e.",
    "This permanently removes every entry from the history. It does not affect files already in the Trash.": "Supprime d\u00e9finitivement chaque entr\u00e9e de l\u2019historique.",
    "Apps you remove with Uninstally will appear here, so you can review or restore them.": "Les apps supprim\u00e9es appara\u00eetront ici.",
    "History Retention": "R\u00e9tention Historique",
    "Automatically remove entries older than this.": "Supprimer automatiquement les entr\u00e9es plus anciennes.",
    "30 Days": "30 Jours",
    "90 Days": "90 Jours",
    "1 Year": "1 An",
    "Forever": "Toujours",
    "Filter history": "Filtrer historique",
    "No Uninstall History": "Aucun Historique",
    "Couldn't Restore": "Restauration Impossible",
    "Apps Uninstalled": "Apps D\u00e9sinstall\u00e9es",
    "Uninstalled": "D\u00e9sinstall\u00e9",
    "Storage Recovered": "Stockage R\u00e9cup\u00e9r\u00e9",
    "Last Uninstall": "Derni\u00e8re D\u00e9sinstallation",
    "Average Recovered": "Moyenne R\u00e9cup\u00e9r\u00e9e",
    "Original Location": "Emplacement d\u2019Origine",
    "Location": "Emplacement",
    "Identifier": "Identifiant",
    "Bundle Identifier": "Identifiant de Bundle",
    "Installed": "Install\u00e9",
    "Last Used": "Derni\u00e8re Utilisation",
    "Volume": "Volume",
    "Today": "Aujourd\u2019hui",
    "Last 7 Days": "7 Derniers Jours",
    "Last 30 Days": "30 Derniers Jours",
    "All Time": "Tout",
    "Trash": "Corbeille",
    "Deleted": "Supprim\u00e9",
    "Permanent Delete": "Suppression D\u00e9finitive",

    "Updates": "Mises \u00e0 Jour",
    "Appearance": "Apparence",
    "Language": "Langue",
    "Uninstall Settings": "Param\u00e8tres D\u00e9sinstallation",
    "Scanning": "Analyse",
    "Security": "S\u00e9curit\u00e9",
    "Advanced": "Avanc\u00e9",
    "About": "\u00c0 propos",
    "Keep Uninstally up to date.": "Garder Uninstally \u00e0 jour.",
    "How Uninstally looks and where it lives.": "Apparence et emplacement d\u2019Uninstally.",
    "Choose the language used throughout the app.": "Choisir la langue de l\u2019application.",
    "What happens when you remove an app.": "Ce qui se passe lors de la suppression.",
    "How thoroughly Uninstally searches for related files.": "Niveau de recherche des fichiers associ\u00e9s.",
    "Confirmations and safe-removal safeguards.": "Confirmations et protections.",
    "Power-user options and resets.": "Options avanc\u00e9es et r\u00e9initialisations.",
    "Version and links.": "Version et liens.",
    "Show icon in Dock": "Afficher l\u2019ic\u00f4ne dans le Dock",
    "When off, Uninstally runs as a lightweight accessory with no Dock or menu-bar presence.": "D\u00e9sactiv\u00e9, Uninstally s\u2019ex\u00e9cute comme accessoire l\u00e9ger.",
    "Source language \u2014 translation ready": "Langue source \u2014 traduction pr\u00eate",
    "The application needs to restart to apply the selected language.": "L\u2019application doit red\u00e9marrer pour appliquer la langue.",
    "Quit after a Finder uninstall": "Quitter apr\u00e8s d\u00e9sinstallation Finder",
    "Automatically close Uninstally once a right-click uninstall finishes.": "Fermer automatiquement Uninstally apr\u00e8s d\u00e9sinstallation.",
    "Keep Uninstall History": "Conserver Historique",
    "Record apps you remove so you can review or restore them from Recently Uninstalled.": "Enregistrer les apps supprim\u00e9es.",
    "Include system-level files": "Inclure les fichiers syst\u00e8me",
    "Also search /Library locations. Removing these requires an administrator password.": "Chercher aussi dans /Library.",
    "Scan for leftovers automatically": "Analyser r\u00e9sidus automatiquement",
    "Look for orphaned files from removed apps in the background.": "Rechercher fichiers orphelins en arri\u00e8re-plan.",
    "Monitor Trash for Deleted Applications": "Surveiller la Corbeille",
    "When you drag an app to the Trash in Finder, offer to remove its leftover files.": "Proposer de supprimer les r\u00e9sidus apr\u00e8s glissement vers la Corbeille.",
    "Require confirmation before deleting": "Exiger confirmation avant suppression",
    "Always show a summary and warning before anything is removed.": "Toujours afficher r\u00e9sum\u00e9 avant suppression.",
    "Verified update source": "Source v\u00e9rifi\u00e9e",
    "Updates are only downloaded from the official Uninstally repository on GitHub and verified before installation.": "Mises \u00e0 jour t\u00e9l\u00e9charg\u00e9es depuis le d\u00e9p\u00f4t officiel.",
    "Reset All Preferences": "R\u00e9initialiser Pr\u00e9f\u00e9rences",
    "Restore Uninstally's settings, sidebar layout and collections to their defaults. Takes effect on next launch.": "Restaurer param\u00e8tres, barre lat\u00e9rale et collections par d\u00e9faut.",
    "Preferences reset. Relaunch to see all changes.": "Pr\u00e9f\u00e9rences r\u00e9initialis\u00e9es.",
    "Current Version": "Version Actuelle",
    "Latest Version": "Derni\u00e8re Version",
    "Last Checked": "Derni\u00e8re V\u00e9rification",
    "Status": "Statut",
    "Automatically Check for Updates": "V\u00e9rifier Mises \u00e0 Jour Auto",
    "Automatically Download Updates": "T\u00e9l\u00e9charger Mises \u00e0 Jour Auto",
    "Receive Beta Updates": "Recevoir Mises \u00e0 Jour Beta",
    "Include pre-release builds from the selected channel.": "Inclure versions pr\u00e9liminaires.",
    "Check Now": "V\u00e9rifier",
    "Clear Ignored Version": "Effacer Version Ignor\u00e9e",
    "Reset Update Preferences": "R\u00e9initialiser Pr\u00e9f. Mises \u00e0 Jour",
    "Update Channel": "Canal de Mise \u00e0 Jour",
    "Enable beta updates to choose a pre-release channel.": "Activer beta pour choisir un canal.",
    "Not checked yet": "Pas encore v\u00e9rifi\u00e9",
    "Checking\u2026": "V\u00e9rification\u2026",
    "You're up to date": "Vous \u00eates \u00e0 jour",
    "Stable": "Stable",
    "Beta": "B\u00eata",
    "Nightly": "Nocturne",
    "Update Available": "Mise \u00e0 Jour Disponible",
    "Update available: %@": "Mise \u00e0 jour disponible\u00a0: %@",

    "Storage Insights": "Analyse Stockage",
    "Installed Applications": "Applications Install\u00e9es",
    "Total Installed Size": "Taille Totale Install\u00e9e",
    "Largest Installed App": "Plus Grande App Install\u00e9e",
    "Total Space Recovered": "Espace Total R\u00e9cup\u00e9r\u00e9",
    "Apps Removed": "Apps Supprim\u00e9es",
    "Average Space Recovered": "Espace Moyen R\u00e9cup\u00e9r\u00e9",
    "Unused Applications": "Applications Inutilis\u00e9es",
    "Largest Applications": "Plus Grandes Applications",
    "Largest Leftover Files": "Plus Grands Fichiers R\u00e9siduels",
    "Not Opened in 90 Days": "Non Ouvertes en 90 Jours",
    "This Week": "Cette Semaine",
    "This Month": "Ce Mois",
    "Lifetime": "Total",
    "Installed %@": "Install\u00e9 %@",
    "Opened %@": "Ouvert %@",
    "Storage by Category": "Stockage par Cat\u00e9gorie",
    "Recovered Storage Over Time": "Stockage R\u00e9cup\u00e9r\u00e9 dans le Temps",
    "Not enough history yet": "Pas assez d\u2019historique",
    "Installed Apps by Developer": "Apps Install\u00e9es par D\u00e9veloppeur",
    "Application Count by Category": "Nombre d\u2019Apps par Cat\u00e9gorie",
    "No data yet": "Pas encore de donn\u00e9es",

    "Homebrew Not Found": "Homebrew Introuvable",
    "Install Homebrew from brew.sh to manage command-line packages and casks here.": "Installez Homebrew depuis brew.sh.",
    "Reading Homebrew packages\u2026": "Lecture paquets Homebrew\u2026",
    "Required by (will break):": "Requis par (cassera)\u00a0:",
    "Depends on:": "D\u00e9pend de\u00a0:",
    "No dependency relationships detected.": "Aucune d\u00e9pendance d\u00e9tect\u00e9e.",
    "Also remove configuration & leftover files (--zap)": "Supprimer aussi config et r\u00e9sidus (--zap)",
    "Cask": "Cask",
    "Formula": "Formule",

    "Scan Leftovers": "Scanner R\u00e9sidus",
    "Dismiss": "Ignorer",
    "Uninstall Complete": "D\u00e9sinstallation Termin\u00e9e",
    "Uninstall Finished with Issues": "D\u00e9sinstallation avec Probl\u00e8mes",
    "Application Moved to Trash": "App Plac\u00e9e dans la Corbeille",
    "Uninstally found leftover files for %@. Would you like to remove them?": "Uninstally a trouv\u00e9 des fichiers r\u00e9siduels pour %@.",

    "Applications and related files will be moved to the Trash. You can restore them until the Trash is emptied.": "Les apps et fichiers seront mis \u00e0 la Corbeille.",
    "Applications and related files will be permanently deleted. This action cannot be undone.": "Les apps et fichiers seront supprim\u00e9s d\u00e9finitivement.",
    "Could not confirm this belongs to %@": "Impossible de confirmer l\u2019appartenance \u00e0 %@",
    "Item still present after deletion": "Fichier toujours pr\u00e9sent apr\u00e8s suppression",
    "Failed to remove %@: %@": "\u00c9chec suppression %@\u00a0: %@",
    "Path no longer exists": "Le chemin n\u2019existe plus",
    "Protected system location": "Emplacement syst\u00e8me prot\u00e9g\u00e9",
    "Too close to a root directory": "Trop proche d\u2019un r\u00e9pertoire racine",
    "Refuses to delete an approved root directory": "Refus de supprimer un r\u00e9pertoire racine approuv\u00e9",
    "Outside every approved location": "Hors de toute zone approuv\u00e9e",
    "Broken alias": "Alias cass\u00e9",
    "The application bundle": "Le bundle de l\u2019application",
    "Named for %@": "Nomm\u00e9 pour %@",
    "Folder named after %@": "Dossier nomm\u00e9 d\u2019apr\u00e8s %@",
    "Preferences for %@": "Pr\u00e9f\u00e9rences pour %@",

    "Homebrew is not installed.": "Homebrew n\u2019est pas install\u00e9.",
    "Uninstall failed.": "\u00c9chec de la d\u00e9sinstallation.",
    "Network error: %@": "Erreur r\u00e9seau\u00a0: %@",
    "Couldn't read the release information from GitHub.": "Impossible de lire les infos de GitHub.",
    "GitHub rate limit reached. Please try again later.": "Limite GitHub atteinte.",
    "The latest release has no downloadable DMG.": "Pas de DMG t\u00e9l\u00e9chargeable.",
    "The update came from an untrusted source and was blocked.": "Source non fiable, mise \u00e0 jour bloqu\u00e9e.",
    "Couldn't mount the downloaded disk image.": "Impossible de monter l\u2019image disque.",
    "The disk image didn't contain Uninstally.": "L\u2019image disque ne contenait pas Uninstally.",
    "Update verification failed: %@": "V\u00e9rification \u00e9chou\u00e9e\u00a0: %@",
    "Couldn't install the update: %@": "Installation \u00e9chou\u00e9e\u00a0: %@",
    "The update was cancelled.": "Mise \u00e0 jour annul\u00e9e.",

    "Sort By": "Trier par",
    "Install Date": "Date d\u2019Installation",
    "Recently Used": "Utilis\u00e9es R\u00e9cemment",
    "Unused": "Inutilis\u00e9es",
    "Change the sort order": "Changer l\u2019ordre de tri",
    "Swap between grid and list": "Basculer grille/liste",
    "Off": "\u00c9teint",
    "On": "Allum\u00e9",
    "Select multiple applications to uninstall together": "S\u00e9lectionner plusieurs applications",
    "Welcome to Uninstally": "Bienvenue dans Uninstally",
    "The cleanest way to completely remove apps and every file they leave behind.": "La fa\u00e7on la plus propre de supprimer les apps.",
    "Smart Detection": "D\u00e9tection Intelligente",
    "Safe by Design": "S\u00e9curis\u00e9 par Conception",
    "You review everything before it's removed. Files go to the Trash where possible, and admin actions ask for permission only when needed.": "Vous v\u00e9rifiez tout avant suppression.",
}

print(f"\nLoaded translations — IT:{len(T['it'])} ES:{len(T['es'])} FR:{len(T['fr'])}")
print("Dictionaries created. Run translate_all.py to apply.")

if __name__ == "__main__":
    print("This module provides translation dictionaries. Import and use.")
