import Foundation

struct FileExplanationEngine {

    func explain(category: RemovalCategory, url: URL, appName: String) -> String {
        switch category {
        case .application:
            return "The \(appName) application bundle."

        case .applicationSupport:
            return "Stores data, plugins, and resources created by \(appName)."

        case .caches:
            return "Temporary files \(appName) uses for performance. These can be recreated automatically."

        case .preferences:
            return "Application settings and user preferences for \(appName)."

        case .savedState:
            return "The previous window state used when reopening \(appName)."

        case .containers:
            return "Sandboxed data managed by macOS for \(appName)."

        case .groupContainers:
            return "Shared sandbox data accessible by \(appName) and its extensions."

        case .logs:
            return "Diagnostic and activity logs generated by \(appName)."

        case .httpStorage:
            return "Web storage and cache data used by \(appName)."

        case .webKit:
            return "Web content and local storage used by \(appName)."

        case .cookies:
            return "Website cookies stored by \(appName)."

        case .temporary:
            return "Temporary files created by \(appName) that are safe to remove."

        case .launchAgents:
            return "A background agent that runs tasks for \(appName) in your user session."

        case .launchDaemons:
            return "A system-level background service installed by \(appName)."

        case .loginItems:
            return "A helper that allows \(appName) to start automatically when you log in."

        case .extensions:
            return "A system extension installed by \(appName) for Finder, QuickLook, or Spotlight."

        case .crashReports:
            return "Crash and diagnostic reports generated when \(appName) encountered an error."

        case .spotlight:
            return "Search index metadata created for \(appName)."

        case .quickLook:
            return "A QuickLook preview plugin installed by \(appName)."

        case .privilegedHelper:
            return "A privileged helper tool installed by \(appName) that runs with elevated permissions."

        case .widgets:
            return "A Notification Center widget provided by \(appName)."

        case .other:
            return "Support files associated with \(appName)."
        }
    }

    func riskLevel(for category: RemovalCategory, requiresAdmin: Bool, isShared: Bool) -> SafetyFactor.Severity {
        if requiresAdmin { return .caution }
        if isShared { return .caution }
        switch category {
        case .launchAgents, .launchDaemons, .privilegedHelper:
            return .warning
        default:
            return .info
        }
    }
}
